//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2022.01.20 at 04:56:34 PM MSK
//

package com.github.akrtkv.semd_demo.dto.semd;

import com.github.akrtkv.semd_demo.dto.semd.address.Type;
import com.github.akrtkv.semd_demo.dto.semd.fias.FiasAddress;

import javax.xml.bind.annotation.*;
import java.util.ArrayList;
import java.util.List;

@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AD_Patient", propOrder = {
        "type",
        "streetAddressLine",
        "stateCode",
        "postalCode",
        "address"
})
public class ADPatient {

    @XmlElement(name = "Type", namespace = "urn:hl7-ru:address")
    protected Type type;

    protected String streetAddressLine;

    @XmlElement(namespace = "urn:hl7-ru:address")
    protected CDAddressStateCode stateCode;

    protected AdxpPostalCode postalCode;

    @XmlElement(name = "Address", namespace = "urn:hl7-ru:fias")
    protected FiasAddress address;

    @XmlAttribute(name = "use")
    protected List<String> use;

    @XmlAttribute(name = "nullFlavor")
    protected List<String> nullFlavor;

    public Type getType() {
        return type;
    }

    public void setType(Type value) {
        this.type = value;
    }

    public String getStreetAddressLine() {
        return streetAddressLine;
    }

    public void setStreetAddressLine(String value) {
        this.streetAddressLine = value;
    }

    public CDAddressStateCode getStateCode() {
        return stateCode;
    }

    public void setStateCode(CDAddressStateCode value) {
        this.stateCode = value;
    }

    public AdxpPostalCode getPostalCode() {
        return postalCode;
    }

    public void setPostalCode(AdxpPostalCode value) {
        this.postalCode = value;
    }

    public FiasAddress getAddress() {
        return address;
    }

    public void setAddress(FiasAddress value) {
        this.address = value;
    }

    public List<String> getUse() {
        if (use == null) {
            use = new ArrayList<String>();
        }
        return this.use;
    }

    public List<String> getNullFlavor() {
        if (nullFlavor == null) {
            nullFlavor = new ArrayList<String>();
        }
        return this.nullFlavor;
    }
}
