//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2022.01.20 at 04:56:34 PM MSK
//

package com.github.akrtkv.semd_demo.dto.semd;

import com.github.akrtkv.semd_demo.dto.semd.address.ResidentCode;
import com.github.akrtkv.semd_demo.dto.semd.address.Type;
import com.github.akrtkv.semd_demo.dto.semd.identity.POCDMT000040DocInfo;
import com.github.akrtkv.semd_demo.dto.semd.identity.POCDMT000040IdentityDoc;
import com.github.akrtkv.semd_demo.dto.semd.identity.POCDMT000040InsurancePolicy;
import com.github.akrtkv.semd_demo.dto.semd.medservice.DocType;

import javax.xml.bind.annotation.*;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;

@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CE_non_elements")
@XmlSeeAlso({
        POCDMT000040ClinicalDocument.Code.class,
        POCDMT000040ClinicalDocument.ConfidentialityCode.class,
        POCDMT000040CodeProfession.class,
        POCDMT000040Patient.AdministrativeGenderCode.class,
        POCDMT000040Section.Code.class,
        POCDMT000040Observation.Code.class,
        POCDMT000040SubstanceAdministration.Code.class,
        POCDMT000040SubstanceAdministration.RouteCode.class,
        POCDMT000040Supply.Code.class,
        POCDMT000040Act.Code.class,
        POCDMT000040Material.Code.class,
        POCDMT000040Criterion.Code.class,
        Type.class,
        ResidentCode.class,
        POCDMT000040IdentityDoc.IdentityCardType.class,
        POCDMT000040InsurancePolicy.InsurancePolicyType.class,
        POCDMT000040DocInfo.IdentityDocType.class,
        POCDMT000040DocInfo.InsurancePolicyType.class,
        DocType.class,
        ServiceForm.class,
        ServiceType.class,
        ServiceCond.class
})
public class CENonElements
        extends ANY {

    @XmlAttribute(name = "code")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String code;

    @XmlAttribute(name = "codeSystem")
    protected String codeSystem;

    @XmlAttribute(name = "codeSystemName")
    protected String codeSystemName;

    @XmlAttribute(name = "codeSystemVersion")
    protected String codeSystemVersion;

    @XmlAttribute(name = "displayName")
    protected String displayName;

    public String getCode() {
        return code;
    }

    public void setCode(String value) {
        this.code = value;
    }

    public String getCodeSystem() {
        return codeSystem;
    }

    public void setCodeSystem(String value) {
        this.codeSystem = value;
    }

    public String getCodeSystemName() {
        return codeSystemName;
    }

    public void setCodeSystemName(String value) {
        this.codeSystemName = value;
    }

    public String getCodeSystemVersion() {
        return codeSystemVersion;
    }

    public void setCodeSystemVersion(String value) {
        this.codeSystemVersion = value;
    }

    public String getDisplayName() {
        return displayName;
    }

    public void setDisplayName(String value) {
        this.displayName = value;
    }
}
