//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2022.01.20 at 04:56:34 PM MSK
//

package com.github.akrtkv.semd_demo.dto.semd;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;

@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CR", propOrder = {
        "name",
        "value"
})
public class CR
        extends ANY {

    protected CV name;

    protected CD value;

    @XmlAttribute(name = "inverted")
    protected Boolean inverted;

    public CV getName() {
        return name;
    }

    public void setName(CV value) {
        this.name = value;
    }

    public CD getValue() {
        return value;
    }

    public void setValue(CD value) {
        this.value = value;
    }

    public boolean isInverted() {
        if (inverted == null) {
            return false;
        } else {
            return inverted;
        }
    }

    public void setInverted(Boolean value) {
        this.inverted = value;
    }
}
