//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2022.01.20 at 04:56:34 PM MSK
//

package com.github.akrtkv.semd_demo.dto.semd;

import javax.xml.bind.annotation.*;
import java.math.BigInteger;

@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "GLIST_TS", propOrder = {
        "head",
        "increment"
})
public class GLISTTS
        extends ANY {

    @XmlElement(required = true)
    protected TS head;

    @XmlElement(required = true)
    protected PQ increment;

    @XmlAttribute(name = "period")
    protected BigInteger period;

    @XmlAttribute(name = "denominator")
    protected BigInteger denominator;

    public TS getHead() {
        return head;
    }

    public void setHead(TS value) {
        this.head = value;
    }

    public PQ getIncrement() {
        return increment;
    }

    public void setIncrement(PQ value) {
        this.increment = value;
    }

    public BigInteger getPeriod() {
        return period;
    }

    public void setPeriod(BigInteger value) {
        this.period = value;
    }

    public BigInteger getDenominator() {
        return denominator;
    }

    public void setDenominator(BigInteger value) {
        this.denominator = value;
    }
}
