//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2022.01.20 at 04:56:34 PM MSK
//

package com.github.akrtkv.semd_demo.dto.semd;

import javax.xml.bind.annotation.*;

@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "II")
@XmlSeeAlso({
        POCDMT000040ClinicalDocument.TypeId.class,
        POCDMT000040ClinicalDocument.TemplateId.class,
        POCDMT000040ClinicalDocument.Id.class,
        POCDMT000040ClinicalDocument.SetId.class,
        IIId.class,
        IIIdPatient.class,
        IIIdOrgNonNF.class,
        IIIdOrg.class,
        POCDMT000040OrganizationPatient.Id.class,
        POCDMT000040CustodianOrganization.Id.class,
        POCDMT000040EncompassingEncounter.Id.class,
        POCDMT000040ExternalDocument.Id.class
})
public class II
        extends ANY {

    @XmlAttribute(name = "root")
    protected String root;

    @XmlAttribute(name = "extension")
    protected String extension;

    @XmlAttribute(name = "assigningAuthorityName")
    protected String assigningAuthorityName;

    @XmlAttribute(name = "displayable")
    protected Boolean displayable;

    public String getRoot() {
        return root;
    }

    public void setRoot(String value) {
        this.root = value;
    }

    public String getExtension() {
        return extension;
    }

    public void setExtension(String value) {
        this.extension = value;
    }

    public String getAssigningAuthorityName() {
        return assigningAuthorityName;
    }

    public void setAssigningAuthorityName(String value) {
        this.assigningAuthorityName = value;
    }

    public Boolean isDisplayable() {
        return displayable;
    }

    public void setDisplayable(Boolean value) {
        this.displayable = value;
    }
}
