//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2022.01.20 at 04:56:34 PM MSK
//

package com.github.akrtkv.semd_demo.dto.semd;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "IVL_TS_1", propOrder = {
        "low",
        "high"
})
public class IVLTS1 {

    @XmlElement(required = true)
    protected Low low;

    protected IVXBTS high;

    public Low getLow() {
        return low;
    }

    public void setLow(Low value) {
        this.low = value;
    }

    public IVXBTS getHigh() {
        return high;
    }

    public void setHigh(IVXBTS value) {
        this.high = value;
    }

    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class Low
            extends IVXBTS {

    }
}
