//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2022.01.20 at 04:56:34 PM MSK
//

package com.github.akrtkv.semd_demo.dto.semd;

import su.medsoft.rir.recipe.dto.iemk_new_edition.fias.FiasAddress;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;

@XmlRegistry
public class ObjectFactory {

    private final static QName _ClinicalDocument_QNAME = new QName("urn:hl7-org:v3", "ClinicalDocument");

    private final static QName _IVLTSLow_QNAME = new QName("urn:hl7-org:v3", "low");

    private final static QName _IVLTSWidth_QNAME = new QName("urn:hl7-org:v3", "width");

    private final static QName _IVLTSHigh_QNAME = new QName("urn:hl7-org:v3", "high");

    private final static QName _IVLTSCenter_QNAME = new QName("urn:hl7-org:v3", "center");

    private final static QName _StrucDocThContent_QNAME = new QName("urn:hl7-org:v3", "content");

    private final static QName _CdContent_QNAME = new QName("urn:hl7-org:v3", "content");

    private final static QName _StContent_QNAME = new QName("urn:hl7-org:v3", "content");

    private final static QName _StrucDocThLinkHtml_QNAME = new QName("urn:hl7-org:v3", "linkHtml");

    private final static QName _StrucDocThSub_QNAME = new QName("urn:hl7-org:v3", "sub");

    private final static QName _StrucDocThSup_QNAME = new QName("urn:hl7-org:v3", "sup");

    private final static QName _StrucDocThBr_QNAME = new QName("urn:hl7-org:v3", "br");

    private final static QName _StrucDocThFootnote_QNAME = new QName("urn:hl7-org:v3", "footnote");

    private final static QName _StrucDocThFootnoteRef_QNAME = new QName("urn:hl7-org:v3", "footnoteRef");

    private final static QName _StrucDocThRenderMultiMedia_QNAME = new QName("urn:hl7-org:v3", "renderMultiMedia");

    private final static QName _StrucDocTdParagraph_QNAME = new QName("urn:hl7-org:v3", "paragraph");

    private final static QName _StrucDocTdList_QNAME = new QName("urn:hl7-org:v3", "list");

    private final static QName _StrucDocParagraphCaption_QNAME = new QName("urn:hl7-org:v3", "caption");

    private final static QName _StrucDocItemTable_QNAME = new QName("urn:hl7-org:v3", "table");

    private final static QName _ADStreetAddressLine_QNAME = new QName("urn:hl7-org:v3", "streetAddressLine");

    private final static QName _ADPostalCode_QNAME = new QName("urn:hl7-org:v3", "postalCode");

    private final static QName _ENFamily_QNAME = new QName("urn:hl7-org:v3", "family");

    private final static QName _ENGiven_QNAME = new QName("urn:hl7-org:v3", "given");

    private final static QName _ENPatronymic_QNAME = new QName("urn:hl7-ru:identity", "Patronymic");

    private final static QName _FiasAddress_QNAME = new QName("urn:hl7-ru:fias", "Address");

    public ObjectFactory() {
    }

    public POCDMT000040Criterion createPOCDMT000040Criterion() {
        return new POCDMT000040Criterion();
    }

    public POCDMT000040ExternalDocument createPOCDMT000040ExternalDocument() {
        return new POCDMT000040ExternalDocument();
    }

    public POCDMT000040Material createPOCDMT000040Material() {
        return new POCDMT000040Material();
    }

    public POCDMT000040Act createPOCDMT000040Act() {
        return new POCDMT000040Act();
    }

    public POCDMT000040Supply createPOCDMT000040Supply() {
        return new POCDMT000040Supply();
    }

    public POCDMT000040SubstanceAdministration createPOCDMT000040SubstanceAdministration() {
        return new POCDMT000040SubstanceAdministration();
    }

    public POCDMT000040Observation createPOCDMT000040Observation() {
        return new POCDMT000040Observation();
    }

    public POCDMT000040Section createPOCDMT000040Section() {
        return new POCDMT000040Section();
    }

    public POCDMT000040EncompassingEncounter createPOCDMT000040EncompassingEncounter() {
        return new POCDMT000040EncompassingEncounter();
    }

    public POCDMT000040EncompassingEncounter.EffectiveTime createPOCDMT000040EncompassingEncounterEffectiveTime() {
        return new POCDMT000040EncompassingEncounter.EffectiveTime();
    }

    public POCDMT000040CustodianOrganization createPOCDMT000040CustodianOrganization() {
        return new POCDMT000040CustodianOrganization();
    }

    public POCDMT000040OrganizationPatient createPOCDMT000040OrganizationPatient() {
        return new POCDMT000040OrganizationPatient();
    }

    public POCDMT000040Patient createPOCDMT000040Patient() {
        return new POCDMT000040Patient();
    }

    public POCDMT000040AssignedEntityLegalAuthenticator createPOCDMT000040AssignedEntityLegalAuthenticator() {
        return new POCDMT000040AssignedEntityLegalAuthenticator();
    }

    public POCDMT000040AssignedEntityLegalAuthenticator.RepresentedOrganization createPOCDMT000040AssignedEntityLegalAuthenticatorRepresentedOrganization() {
        return new POCDMT000040AssignedEntityLegalAuthenticator.RepresentedOrganization();
    }

    public POCDMT000040LegalAuthenticator createPOCDMT000040LegalAuthenticator() {
        return new POCDMT000040LegalAuthenticator();
    }

    public POCDMT000040AssignedAuthor createPOCDMT000040AssignedAuthor() {
        return new POCDMT000040AssignedAuthor();
    }

    public POCDMT000040AssignedEntity createPOCDMT000040AssignedEntity() {
        return new POCDMT000040AssignedEntity();
    }

    public IVLTS1 createIVLTS1() {
        return new IVLTS1();
    }

    public POCDMT000040Organization createPOCDMT000040Organization() {
        return new POCDMT000040Organization();
    }

    public POCDMT000040ClinicalDocument createPOCDMT000040ClinicalDocument() {
        return new POCDMT000040ClinicalDocument();
    }

    public PIVLTS createPIVLTS() {
        return new PIVLTS();
    }

    public EIVLTS createEIVLTS() {
        return new EIVLTS();
    }

    public IVLPQ createIVLPQ() {
        return new IVLPQ();
    }

    public SXCMPQ createSXCMPQ() {
        return new SXCMPQ();
    }

    public IVXBPQ createIVXBPQ() {
        return new IVXBPQ();
    }

    public PPDTS createPPDTS() {
        return new PPDTS();
    }

    public PPDPQ createPPDPQ() {
        return new PPDPQ();
    }

    public PIVLPPDTS createPIVLPPDTS() {
        return new PIVLPPDTS();
    }

    public SXCMPPDTS createSXCMPPDTS() {
        return new SXCMPPDTS();
    }

    public IVLPPDTS createIVLPPDTS() {
        return new IVLPPDTS();
    }

    public IVXBPPDTS createIVXBPPDTS() {
        return new IVXBPPDTS();
    }

    public EIVLPPDTS createEIVLPPDTS() {
        return new EIVLPPDTS();
    }

    public IVLPPDPQ createIVLPPDPQ() {
        return new IVLPPDPQ();
    }

    public SXCMPPDPQ createSXCMPPDPQ() {
        return new SXCMPPDPQ();
    }

    public IVXBPPDPQ createIVXBPPDPQ() {
        return new IVXBPPDPQ();
    }

    public SXPRTS createSXPRTS() {
        return new SXPRTS();
    }

    public SXCMCD createSXCMCD() {
        return new SXCMCD();
    }

    public SXCMMO createSXCMMO() {
        return new SXCMMO();
    }

    public SXCMINT createSXCMINT() {
        return new SXCMINT();
    }

    public SXCMREAL createSXCMREAL() {
        return new SXCMREAL();
    }

    public IVLINT createIVLINT() {
        return new IVLINT();
    }

    public IVXBINT createIVXBINT() {
        return new IVXBINT();
    }

    public IVLREAL createIVLREAL() {
        return new IVLREAL();
    }

    public IVXBREAL createIVXBREAL() {
        return new IVXBREAL();
    }

    public IVLMO createIVLMO() {
        return new IVLMO();
    }

    public IVXBMO createIVXBMO() {
        return new IVXBMO();
    }

    public HXITPQ createHXITPQ() {
        return new HXITPQ();
    }

    public HXITCE createHXITCE() {
        return new HXITCE();
    }

    public BXITCD createBXITCD() {
        return new BXITCD();
    }

    public BXITIVLPQ createBXITIVLPQ() {
        return new BXITIVLPQ();
    }

    public SLISTPQ createSLISTPQ() {
        return new SLISTPQ();
    }

    public SLISTTS createSLISTTS() {
        return new SLISTTS();
    }

    public GLISTTS createGLISTTS() {
        return new GLISTTS();
    }

    public GLISTPQ createGLISTPQ() {
        return new GLISTPQ();
    }

    public RTOPQPQ createRTOPQPQ() {
        return new RTOPQPQ();
    }

    public RTOMOPQ createRTOMOPQ() {
        return new RTOMOPQ();
    }

    public UVPTS createUVPTS() {
        return new UVPTS();
    }

    public BL createBL() {
        return new BL();
    }

    public ANYNonNull createANYNonNull() {
        return new ANYNonNull();
    }

    public BN createBN() {
        return new BN();
    }

    public ED createED() {
        return new ED();
    }

    public Thumbnail createThumbnail() {
        return new Thumbnail();
    }

    public CD createCD() {
        return new CD();
    }

    public CE createCE() {
        return new CE();
    }

    public CV createCV() {
        return new CV();
    }

    public CO createCO() {
        return new CO();
    }

    public CR createCR() {
        return new CR();
    }

    public SC createSC() {
        return new SC();
    }

    public TS createTS() {
        return new TS();
    }

    public ADXP createADXP() {
        return new ADXP();
    }

    public ENXP createENXP() {
        return new ENXP();
    }

    public EnDelimiter createEnDelimiter() {
        return new EnDelimiter();
    }

    public PN createPN() {
        return new PN();
    }

    public INT createINT() {
        return new INT();
    }

    public REAL createREAL() {
        return new REAL();
    }

    public PQR createPQR() {
        return new PQR();
    }

    public PQ createPQ() {
        return new PQ();
    }

    public MO createMO() {
        return new MO();
    }

    public RTO createRTO() {
        return new RTO();
    }

    public EIVLEvent createEIVLEvent() {
        return new EIVLEvent();
    }

    public SXCMTS createSXCMTS() {
        return new SXCMTS();
    }

    public IVLTS createIVLTS() {
        return new IVLTS();
    }

    public IVXBTS createIVXBTS() {
        return new IVXBTS();
    }

    public RTOQTYQTY createRTOQTYQTY() {
        return new RTOQTYQTY();
    }

    public CENonElements createCENonElements() {
        return new CENonElements();
    }

    public POCDMT000040Person createPOCDMT000040Person() {
        return new POCDMT000040Person();
    }

    public POCDMT000040CodeProfession createPOCDMT000040CodeProfession() {
        return new POCDMT000040CodeProfession();
    }

    public POCDMT000040Time createPOCDMT000040Time() {
        return new POCDMT000040Time();
    }

    public IIId createIIId() {
        return new IIId();
    }

    public IIIdPatient createIIIdPatient() {
        return new IIIdPatient();
    }

    public CDAddressStateCode createCDAddressStateCode() {
        return new CDAddressStateCode();
    }

    public IIIdOrgNonNF createIIIdOrgNonNF() {
        return new IIIdOrgNonNF();
    }

    public STNonNF createSTNonNF() {
        return new STNonNF();
    }

    public IIIdOrg createIIIdOrg() {
        return new IIIdOrg();
    }

    public STST createSTST() {
        return new STST();
    }

    public EN createEN() {
        return new EN();
    }

    public AdxpPostalCode createAdxpPostalCode() {
        return new AdxpPostalCode();
    }

    public AD createAD() {
        return new AD();
    }

    public ST createST() {
        return new ST();
    }

    public CS createCS() {
        return new CS();
    }

    public TEL createTEL() {
        return new TEL();
    }

    public II createII() {
        return new II();
    }

    public StrucDocText createStrucDocText() {
        return new StrucDocText();
    }

    public StrucDocTitle createStrucDocTitle() {
        return new StrucDocTitle();
    }

    public StrucDocBr createStrucDocBr() {
        return new StrucDocBr();
    }

    public StrucDocCaption createStrucDocCaption() {
        return new StrucDocCaption();
    }

    public StrucDocCol createStrucDocCol() {
        return new StrucDocCol();
    }

    public StrucDocColgroup createStrucDocColgroup() {
        return new StrucDocColgroup();
    }

    public StrucDocContent createStrucDocContent() {
        return new StrucDocContent();
    }

    public StrucDocTitleContent createStrucDocTitleContent() {
        return new StrucDocTitleContent();
    }

    public StrucDocFootnote createStrucDocFootnote() {
        return new StrucDocFootnote();
    }

    public StrucDocTitleFootnote createStrucDocTitleFootnote() {
        return new StrucDocTitleFootnote();
    }

    public StrucDocFootnoteRef createStrucDocFootnoteRef() {
        return new StrucDocFootnoteRef();
    }

    public StrucDocItem createStrucDocItem() {
        return new StrucDocItem();
    }

    public StrucDocLinkHtml createStrucDocLinkHtml() {
        return new StrucDocLinkHtml();
    }

    public StrucDocList createStrucDocList() {
        return new StrucDocList();
    }

    public StrucDocParagraph createStrucDocParagraph() {
        return new StrucDocParagraph();
    }

    public StrucDocRenderMultiMedia createStrucDocRenderMultiMedia() {
        return new StrucDocRenderMultiMedia();
    }

    public StrucDocSub createStrucDocSub() {
        return new StrucDocSub();
    }

    public StrucDocSup createStrucDocSup() {
        return new StrucDocSup();
    }

    public StrucDocTable createStrucDocTable() {
        return new StrucDocTable();
    }

    public StrucDocTbody createStrucDocTbody() {
        return new StrucDocTbody();
    }

    public StrucDocTd createStrucDocTd() {
        return new StrucDocTd();
    }

    public StrucDocTfoot createStrucDocTfoot() {
        return new StrucDocTfoot();
    }

    public StrucDocTh createStrucDocTh() {
        return new StrucDocTh();
    }

    public StrucDocThead createStrucDocThead() {
        return new StrucDocThead();
    }

    public StrucDocTr createStrucDocTr() {
        return new StrucDocTr();
    }

    public POCDMT000040Author createPOCDMT000040Author() {
        return new POCDMT000040Author();
    }

    public POCDMT000040RecordTarget createPOCDMT000040RecordTarget() {
        return new POCDMT000040RecordTarget();
    }

    public POCDMT000040PatientRole createPOCDMT000040PatientRole() {
        return new POCDMT000040PatientRole();
    }

    public ADPatient createADPatient() {
        return new ADPatient();
    }

    public POCDMT000040Custodian createPOCDMT000040Custodian() {
        return new POCDMT000040Custodian();
    }

    public POCDMT000040AssignedCustodian createPOCDMT000040AssignedCustodian() {
        return new POCDMT000040AssignedCustodian();
    }

    public POCDMT000040InformationRecipient createPOCDMT000040InformationRecipient() {
        return new POCDMT000040InformationRecipient();
    }

    public POCDMT000040IntendedRecipient createPOCDMT000040IntendedRecipient() {
        return new POCDMT000040IntendedRecipient();
    }

    public POCDMT000040OrganizationInformationRecipient createPOCDMT000040OrganizationInformationRecipient() {
        return new POCDMT000040OrganizationInformationRecipient();
    }

    public POCDMT000040Component1 createPOCDMT000040Component1() {
        return new POCDMT000040Component1();
    }

    public POCDMT000040Component2 createPOCDMT000040Component2() {
        return new POCDMT000040Component2();
    }

    public POCDMT000040StructuredBody createPOCDMT000040StructuredBody() {
        return new POCDMT000040StructuredBody();
    }

    public POCDMT000040Component3 createPOCDMT000040Component3() {
        return new POCDMT000040Component3();
    }

    public POCDMT000040Entry createPOCDMT000040Entry() {
        return new POCDMT000040Entry();
    }

    public POCDMT000040Consumable createPOCDMT000040Consumable() {
        return new POCDMT000040Consumable();
    }

    public POCDMT000040Product createPOCDMT000040Product() {
        return new POCDMT000040Product();
    }

    public POCDMT000040ManufacturedProduct createPOCDMT000040ManufacturedProduct() {
        return new POCDMT000040ManufacturedProduct();
    }

    public POCDMT000040EntryRelationship createPOCDMT000040EntryRelationship() {
        return new POCDMT000040EntryRelationship();
    }

    public POCDMT000040Reference createPOCDMT000040Reference() {
        return new POCDMT000040Reference();
    }

    public POCDMT000040SubstanceAdministration1 createPOCDMT000040SubstanceAdministration1() {
        return new POCDMT000040SubstanceAdministration1();
    }

    public POCDMT000040Precondition createPOCDMT000040Precondition() {
        return new POCDMT000040Precondition();
    }

    public POCDMT000040Criterion.Code createPOCDMT000040CriterionCode() {
        return new POCDMT000040Criterion.Code();
    }

    public POCDMT000040ExternalDocument.Id createPOCDMT000040ExternalDocumentId() {
        return new POCDMT000040ExternalDocument.Id();
    }

    public POCDMT000040Material.Code createPOCDMT000040MaterialCode() {
        return new POCDMT000040Material.Code();
    }

    public POCDMT000040Act.Code createPOCDMT000040ActCode() {
        return new POCDMT000040Act.Code();
    }

    public POCDMT000040Supply.Code createPOCDMT000040SupplyCode() {
        return new POCDMT000040Supply.Code();
    }

    public POCDMT000040SubstanceAdministration.Code createPOCDMT000040SubstanceAdministrationCode() {
        return new POCDMT000040SubstanceAdministration.Code();
    }

    public POCDMT000040SubstanceAdministration.RouteCode createPOCDMT000040SubstanceAdministrationRouteCode() {
        return new POCDMT000040SubstanceAdministration.RouteCode();
    }

    public POCDMT000040Observation.Code createPOCDMT000040ObservationCode() {
        return new POCDMT000040Observation.Code();
    }

    public POCDMT000040Observation.EffectiveTime createPOCDMT000040ObservationEffectiveTime() {
        return new POCDMT000040Observation.EffectiveTime();
    }

    public POCDMT000040Section.Code createPOCDMT000040SectionCode() {
        return new POCDMT000040Section.Code();
    }

    public POCDMT000040EncompassingEncounter.Id createPOCDMT000040EncompassingEncounterId() {
        return new POCDMT000040EncompassingEncounter.Id();
    }

    public POCDMT000040EncompassingEncounter.EffectiveTime.Low createPOCDMT000040EncompassingEncounterEffectiveTimeLow() {
        return new POCDMT000040EncompassingEncounter.EffectiveTime.Low();
    }

    public POCDMT000040CustodianOrganization.Id createPOCDMT000040CustodianOrganizationId() {
        return new POCDMT000040CustodianOrganization.Id();
    }

    public POCDMT000040CustodianOrganization.Addr createPOCDMT000040CustodianOrganizationAddr() {
        return new POCDMT000040CustodianOrganization.Addr();
    }

    public POCDMT000040OrganizationPatient.Id createPOCDMT000040OrganizationPatientId() {
        return new POCDMT000040OrganizationPatient.Id();
    }

    public POCDMT000040OrganizationPatient.Addr createPOCDMT000040OrganizationPatientAddr() {
        return new POCDMT000040OrganizationPatient.Addr();
    }

    public POCDMT000040Patient.AdministrativeGenderCode createPOCDMT000040PatientAdministrativeGenderCode() {
        return new POCDMT000040Patient.AdministrativeGenderCode();
    }

    public POCDMT000040AssignedEntityLegalAuthenticator.Addr createPOCDMT000040AssignedEntityLegalAuthenticatorAddr() {
        return new POCDMT000040AssignedEntityLegalAuthenticator.Addr();
    }

    public POCDMT000040AssignedEntityLegalAuthenticator.RepresentedOrganization.Addr createPOCDMT000040AssignedEntityLegalAuthenticatorRepresentedOrganizationAddr() {
        return new POCDMT000040AssignedEntityLegalAuthenticator.RepresentedOrganization.Addr();
    }

    public POCDMT000040LegalAuthenticator.SignatureCode createPOCDMT000040LegalAuthenticatorSignatureCode() {
        return new POCDMT000040LegalAuthenticator.SignatureCode();
    }

    public POCDMT000040AssignedAuthor.Addr createPOCDMT000040AssignedAuthorAddr() {
        return new POCDMT000040AssignedAuthor.Addr();
    }

    public POCDMT000040AssignedAuthor.RepresentedOrganization createPOCDMT000040AssignedAuthorRepresentedOrganization() {
        return new POCDMT000040AssignedAuthor.RepresentedOrganization();
    }

    public POCDMT000040AssignedEntity.Addr createPOCDMT000040AssignedEntityAddr() {
        return new POCDMT000040AssignedEntity.Addr();
    }

    public POCDMT000040AssignedEntity.RepresentedOrganization createPOCDMT000040AssignedEntityRepresentedOrganization() {
        return new POCDMT000040AssignedEntity.RepresentedOrganization();
    }

    public IVLTS1.Low createIVLTS1Low() {
        return new IVLTS1.Low();
    }

    public POCDMT000040Organization.Addr createPOCDMT000040OrganizationAddr() {
        return new POCDMT000040Organization.Addr();
    }

    public POCDMT000040ClinicalDocument.RealmCode createPOCDMT000040ClinicalDocumentRealmCode() {
        return new POCDMT000040ClinicalDocument.RealmCode();
    }

    public POCDMT000040ClinicalDocument.TypeId createPOCDMT000040ClinicalDocumentTypeId() {
        return new POCDMT000040ClinicalDocument.TypeId();
    }

    public POCDMT000040ClinicalDocument.TemplateId createPOCDMT000040ClinicalDocumentTemplateId() {
        return new POCDMT000040ClinicalDocument.TemplateId();
    }

    public POCDMT000040ClinicalDocument.Id createPOCDMT000040ClinicalDocumentId() {
        return new POCDMT000040ClinicalDocument.Id();
    }

    public POCDMT000040ClinicalDocument.Code createPOCDMT000040ClinicalDocumentCode() {
        return new POCDMT000040ClinicalDocument.Code();
    }

    public POCDMT000040ClinicalDocument.EffectiveTime createPOCDMT000040ClinicalDocumentEffectiveTime() {
        return new POCDMT000040ClinicalDocument.EffectiveTime();
    }

    public POCDMT000040ClinicalDocument.ConfidentialityCode createPOCDMT000040ClinicalDocumentConfidentialityCode() {
        return new POCDMT000040ClinicalDocument.ConfidentialityCode();
    }

    public POCDMT000040ClinicalDocument.LanguageCode createPOCDMT000040ClinicalDocumentLanguageCode() {
        return new POCDMT000040ClinicalDocument.LanguageCode();
    }

    public POCDMT000040ClinicalDocument.SetId createPOCDMT000040ClinicalDocumentSetId() {
        return new POCDMT000040ClinicalDocument.SetId();
    }

    public POCDMT000040ClinicalDocument.VersionNumber createPOCDMT000040ClinicalDocumentVersionNumber() {
        return new POCDMT000040ClinicalDocument.VersionNumber();
    }

    @XmlElementDecl(namespace = "urn:hl7-org:v3", name = "ClinicalDocument")
    public JAXBElement<POCDMT000040ClinicalDocument> createClinicalDocument(POCDMT000040ClinicalDocument value) {
        return new JAXBElement<POCDMT000040ClinicalDocument>(_ClinicalDocument_QNAME, POCDMT000040ClinicalDocument.class, null, value);
    }

    @XmlElementDecl(namespace = "urn:hl7-org:v3", name = "low", scope = IVLTS.class)
    public JAXBElement<IVXBTS> createIVLTSLow(IVXBTS value) {
        return new JAXBElement<IVXBTS>(_IVLTSLow_QNAME, IVXBTS.class, IVLTS.class, value);
    }

    @XmlElementDecl(namespace = "urn:hl7-org:v3", name = "width", scope = IVLTS.class)
    public JAXBElement<PQ> createIVLTSWidth(PQ value) {
        return new JAXBElement<PQ>(_IVLTSWidth_QNAME, PQ.class, IVLTS.class, value);
    }

    @XmlElementDecl(namespace = "urn:hl7-org:v3", name = "high", scope = IVLTS.class)
    public JAXBElement<IVXBTS> createIVLTSHigh(IVXBTS value) {
        return new JAXBElement<IVXBTS>(_IVLTSHigh_QNAME, IVXBTS.class, IVLTS.class, value);
    }

    @XmlElementDecl(namespace = "urn:hl7-org:v3", name = "center", scope = IVLTS.class)
    public JAXBElement<TS> createIVLTSCenter(TS value) {
        return new JAXBElement<TS>(_IVLTSCenter_QNAME, TS.class, IVLTS.class, value);
    }

    @XmlElementDecl(namespace = "urn:hl7-org:v3", name = "content", scope = CD.class)
    public JAXBElement<CD> createCdContent(CD value) {
        return new JAXBElement<CD>(_CdContent_QNAME, CD.class, null, value);
    }

    @XmlElementDecl(namespace = "urn:hl7-org:v3", name = "content", scope = ST.class)
    public JAXBElement<ST> createStContent(ST value) {
        return new JAXBElement<ST>(_StContent_QNAME, ST.class, null, value);
    }

    @XmlElementDecl(namespace = "urn:hl7-org:v3", name = "content", scope = StrucDocTh.class)
    public JAXBElement<StrucDocContent> createStrucDocThContent(StrucDocContent value) {
        return new JAXBElement<StrucDocContent>(_StrucDocThContent_QNAME, StrucDocContent.class, StrucDocTh.class, value);
    }

    @XmlElementDecl(namespace = "urn:hl7-org:v3", name = "linkHtml", scope = StrucDocTh.class)
    public JAXBElement<StrucDocLinkHtml> createStrucDocThLinkHtml(StrucDocLinkHtml value) {
        return new JAXBElement<StrucDocLinkHtml>(_StrucDocThLinkHtml_QNAME, StrucDocLinkHtml.class, StrucDocTh.class, value);
    }

    @XmlElementDecl(namespace = "urn:hl7-org:v3", name = "sub", scope = StrucDocTh.class)
    public JAXBElement<StrucDocSub> createStrucDocThSub(StrucDocSub value) {
        return new JAXBElement<StrucDocSub>(_StrucDocThSub_QNAME, StrucDocSub.class, StrucDocTh.class, value);
    }

    @XmlElementDecl(namespace = "urn:hl7-org:v3", name = "sup", scope = StrucDocTh.class)
    public JAXBElement<StrucDocSup> createStrucDocThSup(StrucDocSup value) {
        return new JAXBElement<StrucDocSup>(_StrucDocThSup_QNAME, StrucDocSup.class, StrucDocTh.class, value);
    }

    @XmlElementDecl(namespace = "urn:hl7-org:v3", name = "br", scope = StrucDocTh.class)
    public JAXBElement<StrucDocBr> createStrucDocThBr(StrucDocBr value) {
        return new JAXBElement<StrucDocBr>(_StrucDocThBr_QNAME, StrucDocBr.class, StrucDocTh.class, value);
    }

    @XmlElementDecl(namespace = "urn:hl7-org:v3", name = "footnote", scope = StrucDocTh.class)
    public JAXBElement<StrucDocFootnote> createStrucDocThFootnote(StrucDocFootnote value) {
        return new JAXBElement<StrucDocFootnote>(_StrucDocThFootnote_QNAME, StrucDocFootnote.class, StrucDocTh.class, value);
    }

    @XmlElementDecl(namespace = "urn:hl7-org:v3", name = "footnoteRef", scope = StrucDocTh.class)
    public JAXBElement<StrucDocFootnoteRef> createStrucDocThFootnoteRef(StrucDocFootnoteRef value) {
        return new JAXBElement<StrucDocFootnoteRef>(_StrucDocThFootnoteRef_QNAME, StrucDocFootnoteRef.class, StrucDocTh.class, value);
    }

    @XmlElementDecl(namespace = "urn:hl7-org:v3", name = "renderMultiMedia", scope = StrucDocTh.class)
    public JAXBElement<StrucDocRenderMultiMedia> createStrucDocThRenderMultiMedia(StrucDocRenderMultiMedia value) {
        return new JAXBElement<StrucDocRenderMultiMedia>(_StrucDocThRenderMultiMedia_QNAME, StrucDocRenderMultiMedia.class, StrucDocTh.class, value);
    }

    @XmlElementDecl(namespace = "urn:hl7-org:v3", name = "content", scope = StrucDocTd.class)
    public JAXBElement<StrucDocContent> createStrucDocTdContent(StrucDocContent value) {
        return new JAXBElement<StrucDocContent>(_StrucDocThContent_QNAME, StrucDocContent.class, StrucDocTd.class, value);
    }

    @XmlElementDecl(namespace = "urn:hl7-org:v3", name = "linkHtml", scope = StrucDocTd.class)
    public JAXBElement<StrucDocLinkHtml> createStrucDocTdLinkHtml(StrucDocLinkHtml value) {
        return new JAXBElement<StrucDocLinkHtml>(_StrucDocThLinkHtml_QNAME, StrucDocLinkHtml.class, StrucDocTd.class, value);
    }

    @XmlElementDecl(namespace = "urn:hl7-org:v3", name = "sub", scope = StrucDocTd.class)
    public JAXBElement<StrucDocSub> createStrucDocTdSub(StrucDocSub value) {
        return new JAXBElement<StrucDocSub>(_StrucDocThSub_QNAME, StrucDocSub.class, StrucDocTd.class, value);
    }

    @XmlElementDecl(namespace = "urn:hl7-org:v3", name = "sup", scope = StrucDocTd.class)
    public JAXBElement<StrucDocSup> createStrucDocTdSup(StrucDocSup value) {
        return new JAXBElement<StrucDocSup>(_StrucDocThSup_QNAME, StrucDocSup.class, StrucDocTd.class, value);
    }

    @XmlElementDecl(namespace = "urn:hl7-org:v3", name = "br", scope = StrucDocTd.class)
    public JAXBElement<StrucDocBr> createStrucDocTdBr(StrucDocBr value) {
        return new JAXBElement<StrucDocBr>(_StrucDocThBr_QNAME, StrucDocBr.class, StrucDocTd.class, value);
    }

    @XmlElementDecl(namespace = "urn:hl7-org:v3", name = "footnote", scope = StrucDocTd.class)
    public JAXBElement<StrucDocFootnote> createStrucDocTdFootnote(StrucDocFootnote value) {
        return new JAXBElement<StrucDocFootnote>(_StrucDocThFootnote_QNAME, StrucDocFootnote.class, StrucDocTd.class, value);
    }

    @XmlElementDecl(namespace = "urn:hl7-org:v3", name = "footnoteRef", scope = StrucDocTd.class)
    public JAXBElement<StrucDocFootnoteRef> createStrucDocTdFootnoteRef(StrucDocFootnoteRef value) {
        return new JAXBElement<StrucDocFootnoteRef>(_StrucDocThFootnoteRef_QNAME, StrucDocFootnoteRef.class, StrucDocTd.class, value);
    }

    @XmlElementDecl(namespace = "urn:hl7-org:v3", name = "renderMultiMedia", scope = StrucDocTd.class)
    public JAXBElement<StrucDocRenderMultiMedia> createStrucDocTdRenderMultiMedia(StrucDocRenderMultiMedia value) {
        return new JAXBElement<StrucDocRenderMultiMedia>(_StrucDocThRenderMultiMedia_QNAME, StrucDocRenderMultiMedia.class, StrucDocTd.class, value);
    }

    @XmlElementDecl(namespace = "urn:hl7-org:v3", name = "paragraph", scope = StrucDocTd.class)
    public JAXBElement<StrucDocParagraph> createStrucDocTdParagraph(StrucDocParagraph value) {
        return new JAXBElement<StrucDocParagraph>(_StrucDocTdParagraph_QNAME, StrucDocParagraph.class, StrucDocTd.class, value);
    }

    @XmlElementDecl(namespace = "urn:hl7-org:v3", name = "list", scope = StrucDocTd.class)
    public JAXBElement<StrucDocList> createStrucDocTdList(StrucDocList value) {
        return new JAXBElement<StrucDocList>(_StrucDocTdList_QNAME, StrucDocList.class, StrucDocTd.class, value);
    }

    @XmlElementDecl(namespace = "urn:hl7-org:v3", name = "caption", scope = StrucDocParagraph.class)
    public JAXBElement<StrucDocCaption> createStrucDocParagraphCaption(StrucDocCaption value) {
        return new JAXBElement<StrucDocCaption>(_StrucDocParagraphCaption_QNAME, StrucDocCaption.class, StrucDocParagraph.class, value);
    }

    @XmlElementDecl(namespace = "urn:hl7-org:v3", name = "content", scope = StrucDocParagraph.class)
    public JAXBElement<StrucDocContent> createStrucDocParagraphContent(StrucDocContent value) {
        return new JAXBElement<StrucDocContent>(_StrucDocThContent_QNAME, StrucDocContent.class, StrucDocParagraph.class, value);
    }

    @XmlElementDecl(namespace = "urn:hl7-org:v3", name = "linkHtml", scope = StrucDocParagraph.class)
    public JAXBElement<StrucDocLinkHtml> createStrucDocParagraphLinkHtml(StrucDocLinkHtml value) {
        return new JAXBElement<StrucDocLinkHtml>(_StrucDocThLinkHtml_QNAME, StrucDocLinkHtml.class, StrucDocParagraph.class, value);
    }

    @XmlElementDecl(namespace = "urn:hl7-org:v3", name = "sub", scope = StrucDocParagraph.class)
    public JAXBElement<StrucDocSub> createStrucDocParagraphSub(StrucDocSub value) {
        return new JAXBElement<StrucDocSub>(_StrucDocThSub_QNAME, StrucDocSub.class, StrucDocParagraph.class, value);
    }

    @XmlElementDecl(namespace = "urn:hl7-org:v3", name = "sup", scope = StrucDocParagraph.class)
    public JAXBElement<StrucDocSup> createStrucDocParagraphSup(StrucDocSup value) {
        return new JAXBElement<StrucDocSup>(_StrucDocThSup_QNAME, StrucDocSup.class, StrucDocParagraph.class, value);
    }

    @XmlElementDecl(namespace = "urn:hl7-org:v3", name = "br", scope = StrucDocParagraph.class)
    public JAXBElement<StrucDocBr> createStrucDocParagraphBr(StrucDocBr value) {
        return new JAXBElement<StrucDocBr>(_StrucDocThBr_QNAME, StrucDocBr.class, StrucDocParagraph.class, value);
    }

    @XmlElementDecl(namespace = "urn:hl7-org:v3", name = "footnote", scope = StrucDocParagraph.class)
    public JAXBElement<StrucDocFootnote> createStrucDocParagraphFootnote(StrucDocFootnote value) {
        return new JAXBElement<StrucDocFootnote>(_StrucDocThFootnote_QNAME, StrucDocFootnote.class, StrucDocParagraph.class, value);
    }

    @XmlElementDecl(namespace = "urn:hl7-org:v3", name = "footnoteRef", scope = StrucDocParagraph.class)
    public JAXBElement<StrucDocFootnoteRef> createStrucDocParagraphFootnoteRef(StrucDocFootnoteRef value) {
        return new JAXBElement<StrucDocFootnoteRef>(_StrucDocThFootnoteRef_QNAME, StrucDocFootnoteRef.class, StrucDocParagraph.class, value);
    }

    @XmlElementDecl(namespace = "urn:hl7-org:v3", name = "renderMultiMedia", scope = StrucDocParagraph.class)
    public JAXBElement<StrucDocRenderMultiMedia> createStrucDocParagraphRenderMultiMedia(StrucDocRenderMultiMedia value) {
        return new JAXBElement<StrucDocRenderMultiMedia>(_StrucDocThRenderMultiMedia_QNAME, StrucDocRenderMultiMedia.class, StrucDocParagraph.class, value);
    }

    @XmlElementDecl(namespace = "urn:hl7-org:v3", name = "footnote", scope = StrucDocLinkHtml.class)
    public JAXBElement<StrucDocFootnote> createStrucDocLinkHtmlFootnote(StrucDocFootnote value) {
        return new JAXBElement<StrucDocFootnote>(_StrucDocThFootnote_QNAME, StrucDocFootnote.class, StrucDocLinkHtml.class, value);
    }

    @XmlElementDecl(namespace = "urn:hl7-org:v3", name = "footnoteRef", scope = StrucDocLinkHtml.class)
    public JAXBElement<StrucDocFootnoteRef> createStrucDocLinkHtmlFootnoteRef(StrucDocFootnoteRef value) {
        return new JAXBElement<StrucDocFootnoteRef>(_StrucDocThFootnoteRef_QNAME, StrucDocFootnoteRef.class, StrucDocLinkHtml.class, value);
    }

    @XmlElementDecl(namespace = "urn:hl7-org:v3", name = "caption", scope = StrucDocItem.class)
    public JAXBElement<StrucDocCaption> createStrucDocItemCaption(StrucDocCaption value) {
        return new JAXBElement<StrucDocCaption>(_StrucDocParagraphCaption_QNAME, StrucDocCaption.class, StrucDocItem.class, value);
    }

    @XmlElementDecl(namespace = "urn:hl7-org:v3", name = "content", scope = StrucDocItem.class)
    public JAXBElement<StrucDocContent> createStrucDocItemContent(StrucDocContent value) {
        return new JAXBElement<StrucDocContent>(_StrucDocThContent_QNAME, StrucDocContent.class, StrucDocItem.class, value);
    }

    @XmlElementDecl(namespace = "urn:hl7-org:v3", name = "linkHtml", scope = StrucDocItem.class)
    public JAXBElement<StrucDocLinkHtml> createStrucDocItemLinkHtml(StrucDocLinkHtml value) {
        return new JAXBElement<StrucDocLinkHtml>(_StrucDocThLinkHtml_QNAME, StrucDocLinkHtml.class, StrucDocItem.class, value);
    }

    @XmlElementDecl(namespace = "urn:hl7-org:v3", name = "sub", scope = StrucDocItem.class)
    public JAXBElement<StrucDocSub> createStrucDocItemSub(StrucDocSub value) {
        return new JAXBElement<StrucDocSub>(_StrucDocThSub_QNAME, StrucDocSub.class, StrucDocItem.class, value);
    }

    @XmlElementDecl(namespace = "urn:hl7-org:v3", name = "sup", scope = StrucDocItem.class)
    public JAXBElement<StrucDocSup> createStrucDocItemSup(StrucDocSup value) {
        return new JAXBElement<StrucDocSup>(_StrucDocThSup_QNAME, StrucDocSup.class, StrucDocItem.class, value);
    }

    @XmlElementDecl(namespace = "urn:hl7-org:v3", name = "br", scope = StrucDocItem.class)
    public JAXBElement<StrucDocBr> createStrucDocItemBr(StrucDocBr value) {
        return new JAXBElement<StrucDocBr>(_StrucDocThBr_QNAME, StrucDocBr.class, StrucDocItem.class, value);
    }

    @XmlElementDecl(namespace = "urn:hl7-org:v3", name = "footnote", scope = StrucDocItem.class)
    public JAXBElement<StrucDocFootnote> createStrucDocItemFootnote(StrucDocFootnote value) {
        return new JAXBElement<StrucDocFootnote>(_StrucDocThFootnote_QNAME, StrucDocFootnote.class, StrucDocItem.class, value);
    }

    @XmlElementDecl(namespace = "urn:hl7-org:v3", name = "footnoteRef", scope = StrucDocItem.class)
    public JAXBElement<StrucDocFootnoteRef> createStrucDocItemFootnoteRef(StrucDocFootnoteRef value) {
        return new JAXBElement<StrucDocFootnoteRef>(_StrucDocThFootnoteRef_QNAME, StrucDocFootnoteRef.class, StrucDocItem.class, value);
    }

    @XmlElementDecl(namespace = "urn:hl7-org:v3", name = "renderMultiMedia", scope = StrucDocItem.class)
    public JAXBElement<StrucDocRenderMultiMedia> createStrucDocItemRenderMultiMedia(StrucDocRenderMultiMedia value) {
        return new JAXBElement<StrucDocRenderMultiMedia>(_StrucDocThRenderMultiMedia_QNAME, StrucDocRenderMultiMedia.class, StrucDocItem.class, value);
    }

    @XmlElementDecl(namespace = "urn:hl7-org:v3", name = "paragraph", scope = StrucDocItem.class)
    public JAXBElement<StrucDocParagraph> createStrucDocItemParagraph(StrucDocParagraph value) {
        return new JAXBElement<StrucDocParagraph>(_StrucDocTdParagraph_QNAME, StrucDocParagraph.class, StrucDocItem.class, value);
    }

    @XmlElementDecl(namespace = "urn:hl7-org:v3", name = "list", scope = StrucDocItem.class)
    public JAXBElement<StrucDocList> createStrucDocItemList(StrucDocList value) {
        return new JAXBElement<StrucDocList>(_StrucDocTdList_QNAME, StrucDocList.class, StrucDocItem.class, value);
    }

    @XmlElementDecl(namespace = "urn:hl7-org:v3", name = "table", scope = StrucDocItem.class)
    public JAXBElement<StrucDocTable> createStrucDocItemTable(StrucDocTable value) {
        return new JAXBElement<StrucDocTable>(_StrucDocItemTable_QNAME, StrucDocTable.class, StrucDocItem.class, value);
    }

    @XmlElementDecl(namespace = "urn:hl7-org:v3", name = "content", scope = StrucDocTitleFootnote.class)
    public JAXBElement<StrucDocTitleContent> createStrucDocTitleFootnoteContent(StrucDocTitleContent value) {
        return new JAXBElement<StrucDocTitleContent>(_StrucDocThContent_QNAME, StrucDocTitleContent.class, StrucDocTitleFootnote.class, value);
    }

    @XmlElementDecl(namespace = "urn:hl7-org:v3", name = "sub", scope = StrucDocTitleFootnote.class)
    public JAXBElement<StrucDocSub> createStrucDocTitleFootnoteSub(StrucDocSub value) {
        return new JAXBElement<StrucDocSub>(_StrucDocThSub_QNAME, StrucDocSub.class, StrucDocTitleFootnote.class, value);
    }

    @XmlElementDecl(namespace = "urn:hl7-org:v3", name = "sup", scope = StrucDocTitleFootnote.class)
    public JAXBElement<StrucDocSup> createStrucDocTitleFootnoteSup(StrucDocSup value) {
        return new JAXBElement<StrucDocSup>(_StrucDocThSup_QNAME, StrucDocSup.class, StrucDocTitleFootnote.class, value);
    }

    @XmlElementDecl(namespace = "urn:hl7-org:v3", name = "br", scope = StrucDocTitleFootnote.class)
    public JAXBElement<StrucDocBr> createStrucDocTitleFootnoteBr(StrucDocBr value) {
        return new JAXBElement<StrucDocBr>(_StrucDocThBr_QNAME, StrucDocBr.class, StrucDocTitleFootnote.class, value);
    }

    @XmlElementDecl(namespace = "urn:hl7-org:v3", name = "content", scope = StrucDocFootnote.class)
    public JAXBElement<StrucDocContent> createStrucDocFootnoteContent(StrucDocContent value) {
        return new JAXBElement<StrucDocContent>(_StrucDocThContent_QNAME, StrucDocContent.class, StrucDocFootnote.class, value);
    }

    @XmlElementDecl(namespace = "urn:hl7-org:v3", name = "linkHtml", scope = StrucDocFootnote.class)
    public JAXBElement<StrucDocLinkHtml> createStrucDocFootnoteLinkHtml(StrucDocLinkHtml value) {
        return new JAXBElement<StrucDocLinkHtml>(_StrucDocThLinkHtml_QNAME, StrucDocLinkHtml.class, StrucDocFootnote.class, value);
    }

    @XmlElementDecl(namespace = "urn:hl7-org:v3", name = "sub", scope = StrucDocFootnote.class)
    public JAXBElement<StrucDocSub> createStrucDocFootnoteSub(StrucDocSub value) {
        return new JAXBElement<StrucDocSub>(_StrucDocThSub_QNAME, StrucDocSub.class, StrucDocFootnote.class, value);
    }

    @XmlElementDecl(namespace = "urn:hl7-org:v3", name = "sup", scope = StrucDocFootnote.class)
    public JAXBElement<StrucDocSup> createStrucDocFootnoteSup(StrucDocSup value) {
        return new JAXBElement<StrucDocSup>(_StrucDocThSup_QNAME, StrucDocSup.class, StrucDocFootnote.class, value);
    }

    @XmlElementDecl(namespace = "urn:hl7-org:v3", name = "br", scope = StrucDocFootnote.class)
    public JAXBElement<StrucDocBr> createStrucDocFootnoteBr(StrucDocBr value) {
        return new JAXBElement<StrucDocBr>(_StrucDocThBr_QNAME, StrucDocBr.class, StrucDocFootnote.class, value);
    }

    @XmlElementDecl(namespace = "urn:hl7-org:v3", name = "renderMultiMedia", scope = StrucDocFootnote.class)
    public JAXBElement<StrucDocRenderMultiMedia> createStrucDocFootnoteRenderMultiMedia(StrucDocRenderMultiMedia value) {
        return new JAXBElement<StrucDocRenderMultiMedia>(_StrucDocThRenderMultiMedia_QNAME, StrucDocRenderMultiMedia.class, StrucDocFootnote.class, value);
    }

    @XmlElementDecl(namespace = "urn:hl7-org:v3", name = "paragraph", scope = StrucDocFootnote.class)
    public JAXBElement<StrucDocParagraph> createStrucDocFootnoteParagraph(StrucDocParagraph value) {
        return new JAXBElement<StrucDocParagraph>(_StrucDocTdParagraph_QNAME, StrucDocParagraph.class, StrucDocFootnote.class, value);
    }

    @XmlElementDecl(namespace = "urn:hl7-org:v3", name = "list", scope = StrucDocFootnote.class)
    public JAXBElement<StrucDocList> createStrucDocFootnoteList(StrucDocList value) {
        return new JAXBElement<StrucDocList>(_StrucDocTdList_QNAME, StrucDocList.class, StrucDocFootnote.class, value);
    }

    @XmlElementDecl(namespace = "urn:hl7-org:v3", name = "table", scope = StrucDocFootnote.class)
    public JAXBElement<StrucDocTable> createStrucDocFootnoteTable(StrucDocTable value) {
        return new JAXBElement<StrucDocTable>(_StrucDocItemTable_QNAME, StrucDocTable.class, StrucDocFootnote.class, value);
    }

    @XmlElementDecl(namespace = "urn:hl7-org:v3", name = "content", scope = StrucDocTitleContent.class)
    public JAXBElement<StrucDocTitleContent> createStrucDocTitleContentContent(StrucDocTitleContent value) {
        return new JAXBElement<StrucDocTitleContent>(_StrucDocThContent_QNAME, StrucDocTitleContent.class, StrucDocTitleContent.class, value);
    }

    @XmlElementDecl(namespace = "urn:hl7-org:v3", name = "sub", scope = StrucDocTitleContent.class)
    public JAXBElement<StrucDocSub> createStrucDocTitleContentSub(StrucDocSub value) {
        return new JAXBElement<StrucDocSub>(_StrucDocThSub_QNAME, StrucDocSub.class, StrucDocTitleContent.class, value);
    }

    @XmlElementDecl(namespace = "urn:hl7-org:v3", name = "sup", scope = StrucDocTitleContent.class)
    public JAXBElement<StrucDocSup> createStrucDocTitleContentSup(StrucDocSup value) {
        return new JAXBElement<StrucDocSup>(_StrucDocThSup_QNAME, StrucDocSup.class, StrucDocTitleContent.class, value);
    }

    @XmlElementDecl(namespace = "urn:hl7-org:v3", name = "br", scope = StrucDocTitleContent.class)
    public JAXBElement<StrucDocBr> createStrucDocTitleContentBr(StrucDocBr value) {
        return new JAXBElement<StrucDocBr>(_StrucDocThBr_QNAME, StrucDocBr.class, StrucDocTitleContent.class, value);
    }

    @XmlElementDecl(namespace = "urn:hl7-org:v3", name = "footnote", scope = StrucDocTitleContent.class)
    public JAXBElement<StrucDocTitleFootnote> createStrucDocTitleContentFootnote(StrucDocTitleFootnote value) {
        return new JAXBElement<StrucDocTitleFootnote>(_StrucDocThFootnote_QNAME, StrucDocTitleFootnote.class, StrucDocTitleContent.class, value);
    }

    @XmlElementDecl(namespace = "urn:hl7-org:v3", name = "footnoteRef", scope = StrucDocTitleContent.class)
    public JAXBElement<StrucDocFootnoteRef> createStrucDocTitleContentFootnoteRef(StrucDocFootnoteRef value) {
        return new JAXBElement<StrucDocFootnoteRef>(_StrucDocThFootnoteRef_QNAME, StrucDocFootnoteRef.class, StrucDocTitleContent.class, value);
    }

    @XmlElementDecl(namespace = "urn:hl7-org:v3", name = "content", scope = StrucDocContent.class)
    public JAXBElement<StrucDocContent> createStrucDocContentContent(StrucDocContent value) {
        return new JAXBElement<StrucDocContent>(_StrucDocThContent_QNAME, StrucDocContent.class, StrucDocContent.class, value);
    }

    @XmlElementDecl(namespace = "urn:hl7-org:v3", name = "linkHtml", scope = StrucDocContent.class)
    public JAXBElement<StrucDocLinkHtml> createStrucDocContentLinkHtml(StrucDocLinkHtml value) {
        return new JAXBElement<StrucDocLinkHtml>(_StrucDocThLinkHtml_QNAME, StrucDocLinkHtml.class, StrucDocContent.class, value);
    }

    @XmlElementDecl(namespace = "urn:hl7-org:v3", name = "sub", scope = StrucDocContent.class)
    public JAXBElement<StrucDocSub> createStrucDocContentSub(StrucDocSub value) {
        return new JAXBElement<StrucDocSub>(_StrucDocThSub_QNAME, StrucDocSub.class, StrucDocContent.class, value);
    }

    @XmlElementDecl(namespace = "urn:hl7-org:v3", name = "sup", scope = StrucDocContent.class)
    public JAXBElement<StrucDocSup> createStrucDocContentSup(StrucDocSup value) {
        return new JAXBElement<StrucDocSup>(_StrucDocThSup_QNAME, StrucDocSup.class, StrucDocContent.class, value);
    }

    @XmlElementDecl(namespace = "urn:hl7-org:v3", name = "br", scope = StrucDocContent.class)
    public JAXBElement<StrucDocBr> createStrucDocContentBr(StrucDocBr value) {
        return new JAXBElement<StrucDocBr>(_StrucDocThBr_QNAME, StrucDocBr.class, StrucDocContent.class, value);
    }

    @XmlElementDecl(namespace = "urn:hl7-org:v3", name = "footnote", scope = StrucDocContent.class)
    public JAXBElement<StrucDocFootnote> createStrucDocContentFootnote(StrucDocFootnote value) {
        return new JAXBElement<StrucDocFootnote>(_StrucDocThFootnote_QNAME, StrucDocFootnote.class, StrucDocContent.class, value);
    }

    @XmlElementDecl(namespace = "urn:hl7-org:v3", name = "footnoteRef", scope = StrucDocContent.class)
    public JAXBElement<StrucDocFootnoteRef> createStrucDocContentFootnoteRef(StrucDocFootnoteRef value) {
        return new JAXBElement<StrucDocFootnoteRef>(_StrucDocThFootnoteRef_QNAME, StrucDocFootnoteRef.class, StrucDocContent.class, value);
    }

    @XmlElementDecl(namespace = "urn:hl7-org:v3", name = "renderMultiMedia", scope = StrucDocContent.class)
    public JAXBElement<StrucDocRenderMultiMedia> createStrucDocContentRenderMultiMedia(StrucDocRenderMultiMedia value) {
        return new JAXBElement<StrucDocRenderMultiMedia>(_StrucDocThRenderMultiMedia_QNAME, StrucDocRenderMultiMedia.class, StrucDocContent.class, value);
    }

    @XmlElementDecl(namespace = "urn:hl7-org:v3", name = "linkHtml", scope = StrucDocCaption.class)
    public JAXBElement<StrucDocLinkHtml> createStrucDocCaptionLinkHtml(StrucDocLinkHtml value) {
        return new JAXBElement<StrucDocLinkHtml>(_StrucDocThLinkHtml_QNAME, StrucDocLinkHtml.class, StrucDocCaption.class, value);
    }

    @XmlElementDecl(namespace = "urn:hl7-org:v3", name = "sub", scope = StrucDocCaption.class)
    public JAXBElement<StrucDocSub> createStrucDocCaptionSub(StrucDocSub value) {
        return new JAXBElement<StrucDocSub>(_StrucDocThSub_QNAME, StrucDocSub.class, StrucDocCaption.class, value);
    }

    @XmlElementDecl(namespace = "urn:hl7-org:v3", name = "sup", scope = StrucDocCaption.class)
    public JAXBElement<StrucDocSup> createStrucDocCaptionSup(StrucDocSup value) {
        return new JAXBElement<StrucDocSup>(_StrucDocThSup_QNAME, StrucDocSup.class, StrucDocCaption.class, value);
    }

    @XmlElementDecl(namespace = "urn:hl7-org:v3", name = "footnote", scope = StrucDocCaption.class)
    public JAXBElement<StrucDocFootnote> createStrucDocCaptionFootnote(StrucDocFootnote value) {
        return new JAXBElement<StrucDocFootnote>(_StrucDocThFootnote_QNAME, StrucDocFootnote.class, StrucDocCaption.class, value);
    }

    @XmlElementDecl(namespace = "urn:hl7-org:v3", name = "footnoteRef", scope = StrucDocCaption.class)
    public JAXBElement<StrucDocFootnoteRef> createStrucDocCaptionFootnoteRef(StrucDocFootnoteRef value) {
        return new JAXBElement<StrucDocFootnoteRef>(_StrucDocThFootnoteRef_QNAME, StrucDocFootnoteRef.class, StrucDocCaption.class, value);
    }

    @XmlElementDecl(namespace = "urn:hl7-org:v3", name = "content", scope = StrucDocTitle.class)
    public JAXBElement<StrucDocTitleContent> createStrucDocTitleContent(StrucDocTitleContent value) {
        return new JAXBElement<StrucDocTitleContent>(_StrucDocThContent_QNAME, StrucDocTitleContent.class, StrucDocTitle.class, value);
    }

    @XmlElementDecl(namespace = "urn:hl7-org:v3", name = "sub", scope = StrucDocTitle.class)
    public JAXBElement<StrucDocSub> createStrucDocTitleSub(StrucDocSub value) {
        return new JAXBElement<StrucDocSub>(_StrucDocThSub_QNAME, StrucDocSub.class, StrucDocTitle.class, value);
    }

    @XmlElementDecl(namespace = "urn:hl7-org:v3", name = "sup", scope = StrucDocTitle.class)
    public JAXBElement<StrucDocSup> createStrucDocTitleSup(StrucDocSup value) {
        return new JAXBElement<StrucDocSup>(_StrucDocThSup_QNAME, StrucDocSup.class, StrucDocTitle.class, value);
    }

    @XmlElementDecl(namespace = "urn:hl7-org:v3", name = "br", scope = StrucDocTitle.class)
    public JAXBElement<StrucDocBr> createStrucDocTitleBr(StrucDocBr value) {
        return new JAXBElement<StrucDocBr>(_StrucDocThBr_QNAME, StrucDocBr.class, StrucDocTitle.class, value);
    }

    @XmlElementDecl(namespace = "urn:hl7-org:v3", name = "footnote", scope = StrucDocTitle.class)
    public JAXBElement<StrucDocTitleFootnote> createStrucDocTitleFootnote(StrucDocTitleFootnote value) {
        return new JAXBElement<StrucDocTitleFootnote>(_StrucDocThFootnote_QNAME, StrucDocTitleFootnote.class, StrucDocTitle.class, value);
    }

    @XmlElementDecl(namespace = "urn:hl7-org:v3", name = "footnoteRef", scope = StrucDocTitle.class)
    public JAXBElement<StrucDocFootnoteRef> createStrucDocTitleFootnoteRef(StrucDocFootnoteRef value) {
        return new JAXBElement<StrucDocFootnoteRef>(_StrucDocThFootnoteRef_QNAME, StrucDocFootnoteRef.class, StrucDocTitle.class, value);
    }

    @XmlElementDecl(namespace = "urn:hl7-org:v3", name = "content", scope = StrucDocText.class)
    public JAXBElement<StrucDocContent> createStrucDocTextContent(StrucDocContent value) {
        return new JAXBElement<StrucDocContent>(_StrucDocThContent_QNAME, StrucDocContent.class, StrucDocText.class, value);
    }

    @XmlElementDecl(namespace = "urn:hl7-org:v3", name = "linkHtml", scope = StrucDocText.class)
    public JAXBElement<StrucDocLinkHtml> createStrucDocTextLinkHtml(StrucDocLinkHtml value) {
        return new JAXBElement<StrucDocLinkHtml>(_StrucDocThLinkHtml_QNAME, StrucDocLinkHtml.class, StrucDocText.class, value);
    }

    @XmlElementDecl(namespace = "urn:hl7-org:v3", name = "sub", scope = StrucDocText.class)
    public JAXBElement<StrucDocSub> createStrucDocTextSub(StrucDocSub value) {
        return new JAXBElement<StrucDocSub>(_StrucDocThSub_QNAME, StrucDocSub.class, StrucDocText.class, value);
    }

    @XmlElementDecl(namespace = "urn:hl7-org:v3", name = "sup", scope = StrucDocText.class)
    public JAXBElement<StrucDocSup> createStrucDocTextSup(StrucDocSup value) {
        return new JAXBElement<StrucDocSup>(_StrucDocThSup_QNAME, StrucDocSup.class, StrucDocText.class, value);
    }

    @XmlElementDecl(namespace = "urn:hl7-org:v3", name = "br", scope = StrucDocText.class)
    public JAXBElement<StrucDocBr> createStrucDocTextBr(StrucDocBr value) {
        return new JAXBElement<StrucDocBr>(_StrucDocThBr_QNAME, StrucDocBr.class, StrucDocText.class, value);
    }

    @XmlElementDecl(namespace = "urn:hl7-org:v3", name = "footnote", scope = StrucDocText.class)
    public JAXBElement<StrucDocFootnote> createStrucDocTextFootnote(StrucDocFootnote value) {
        return new JAXBElement<StrucDocFootnote>(_StrucDocThFootnote_QNAME, StrucDocFootnote.class, StrucDocText.class, value);
    }

    @XmlElementDecl(namespace = "urn:hl7-org:v3", name = "footnoteRef", scope = StrucDocText.class)
    public JAXBElement<StrucDocFootnoteRef> createStrucDocTextFootnoteRef(StrucDocFootnoteRef value) {
        return new JAXBElement<StrucDocFootnoteRef>(_StrucDocThFootnoteRef_QNAME, StrucDocFootnoteRef.class, StrucDocText.class, value);
    }

    @XmlElementDecl(namespace = "urn:hl7-org:v3", name = "renderMultiMedia", scope = StrucDocText.class)
    public JAXBElement<StrucDocRenderMultiMedia> createStrucDocTextRenderMultiMedia(StrucDocRenderMultiMedia value) {
        return new JAXBElement<StrucDocRenderMultiMedia>(_StrucDocThRenderMultiMedia_QNAME, StrucDocRenderMultiMedia.class, StrucDocText.class, value);
    }

    @XmlElementDecl(namespace = "urn:hl7-org:v3", name = "paragraph", scope = StrucDocText.class)
    public JAXBElement<StrucDocParagraph> createStrucDocTextParagraph(StrucDocParagraph value) {
        return new JAXBElement<StrucDocParagraph>(_StrucDocTdParagraph_QNAME, StrucDocParagraph.class, StrucDocText.class, value);
    }

    @XmlElementDecl(namespace = "urn:hl7-org:v3", name = "list", scope = StrucDocText.class)
    public JAXBElement<StrucDocList> createStrucDocTextList(StrucDocList value) {
        return new JAXBElement<StrucDocList>(_StrucDocTdList_QNAME, StrucDocList.class, StrucDocText.class, value);
    }

    @XmlElementDecl(namespace = "urn:hl7-org:v3", name = "table", scope = StrucDocText.class)
    public JAXBElement<StrucDocTable> createStrucDocTextTable(StrucDocTable value) {
        return new JAXBElement<StrucDocTable>(_StrucDocItemTable_QNAME, StrucDocTable.class, StrucDocText.class, value);
    }

    @XmlElementDecl(namespace = "urn:hl7-org:v3", name = "streetAddressLine", scope = AD.class)
    public JAXBElement<String> createADStreetAddressLine(String value) {
        return new JAXBElement<String>(_ADStreetAddressLine_QNAME, String.class, AD.class, value);
    }

    @XmlElementDecl(namespace = "urn:hl7-org:v3", name = "postalCode", scope = AD.class)
    public JAXBElement<AdxpPostalCode> createADPostalCode(AdxpPostalCode value) {
        return new JAXBElement<AdxpPostalCode>(_ADPostalCode_QNAME, AdxpPostalCode.class, AD.class, value);
    }

    @XmlElementDecl(namespace = "urn:hl7-org:v3", name = "family", scope = EN.class)
    public JAXBElement<String> createENFamily(String value) {
        return new JAXBElement<String>(_ENFamily_QNAME, String.class, EN.class, value);
    }

    @XmlElementDecl(namespace = "urn:hl7-org:v3", name = "given", scope = EN.class)
    public JAXBElement<String> createENGiven(String value) {
        return new JAXBElement<String>(_ENGiven_QNAME, String.class, EN.class, value);
    }

    @XmlElementDecl(namespace = "urn:hl7-ru:identity", name = "Patronymic", scope = EN.class)
    public JAXBElement<String> createENPatronymic(String value) {
        return new JAXBElement<String>(_ENPatronymic_QNAME, String.class, EN.class, value);
    }

    @XmlElementDecl(namespace = "urn:hl7-ru:fias", name = "Address", scope = FiasAddress.class)
    public JAXBElement<FiasAddress> createFiasAddress(FiasAddress value) {
        return new JAXBElement<FiasAddress>(_FiasAddress_QNAME, FiasAddress.class, null, value);
    }

    @XmlElementDecl(namespace = "urn:hl7-org:v3", name = "low", scope = IVLPQ.class)
    public JAXBElement<IVXBPQ> createIVLPQLow(IVXBPQ value) {
        return new JAXBElement<IVXBPQ>(_IVLTSLow_QNAME, IVXBPQ.class, IVLPQ.class, value);
    }

    @XmlElementDecl(namespace = "urn:hl7-org:v3", name = "width", scope = IVLPQ.class)
    public JAXBElement<PQ> createIVLPQWidth(PQ value) {
        return new JAXBElement<PQ>(_IVLTSWidth_QNAME, PQ.class, IVLPQ.class, value);
    }

    @XmlElementDecl(namespace = "urn:hl7-org:v3", name = "high", scope = IVLPQ.class)
    public JAXBElement<IVXBPQ> createIVLPQHigh(IVXBPQ value) {
        return new JAXBElement<IVXBPQ>(_IVLTSHigh_QNAME, IVXBPQ.class, IVLPQ.class, value);
    }

    @XmlElementDecl(namespace = "urn:hl7-org:v3", name = "center", scope = IVLPQ.class)
    public JAXBElement<PQ> createIVLPQCenter(PQ value) {
        return new JAXBElement<PQ>(_IVLTSCenter_QNAME, PQ.class, IVLPQ.class, value);
    }

    @XmlElementDecl(namespace = "urn:hl7-org:v3", name = "low", scope = IVLMO.class)
    public JAXBElement<IVXBMO> createIVLMOLow(IVXBMO value) {
        return new JAXBElement<IVXBMO>(_IVLTSLow_QNAME, IVXBMO.class, IVLMO.class, value);
    }

    @XmlElementDecl(namespace = "urn:hl7-org:v3", name = "width", scope = IVLMO.class)
    public JAXBElement<MO> createIVLMOWidth(MO value) {
        return new JAXBElement<MO>(_IVLTSWidth_QNAME, MO.class, IVLMO.class, value);
    }

    @XmlElementDecl(namespace = "urn:hl7-org:v3", name = "high", scope = IVLMO.class)
    public JAXBElement<IVXBMO> createIVLMOHigh(IVXBMO value) {
        return new JAXBElement<IVXBMO>(_IVLTSHigh_QNAME, IVXBMO.class, IVLMO.class, value);
    }

    @XmlElementDecl(namespace = "urn:hl7-org:v3", name = "center", scope = IVLMO.class)
    public JAXBElement<MO> createIVLMOCenter(MO value) {
        return new JAXBElement<MO>(_IVLTSCenter_QNAME, MO.class, IVLMO.class, value);
    }

    @XmlElementDecl(namespace = "urn:hl7-org:v3", name = "low", scope = IVLREAL.class)
    public JAXBElement<IVXBREAL> createIVLREALLow(IVXBREAL value) {
        return new JAXBElement<IVXBREAL>(_IVLTSLow_QNAME, IVXBREAL.class, IVLREAL.class, value);
    }

    @XmlElementDecl(namespace = "urn:hl7-org:v3", name = "width", scope = IVLREAL.class)
    public JAXBElement<REAL> createIVLREALWidth(REAL value) {
        return new JAXBElement<REAL>(_IVLTSWidth_QNAME, REAL.class, IVLREAL.class, value);
    }

    @XmlElementDecl(namespace = "urn:hl7-org:v3", name = "high", scope = IVLREAL.class)
    public JAXBElement<IVXBREAL> createIVLREALHigh(IVXBREAL value) {
        return new JAXBElement<IVXBREAL>(_IVLTSHigh_QNAME, IVXBREAL.class, IVLREAL.class, value);
    }

    @XmlElementDecl(namespace = "urn:hl7-org:v3", name = "center", scope = IVLREAL.class)
    public JAXBElement<REAL> createIVLREALCenter(REAL value) {
        return new JAXBElement<REAL>(_IVLTSCenter_QNAME, REAL.class, IVLREAL.class, value);
    }

    @XmlElementDecl(namespace = "urn:hl7-org:v3", name = "low", scope = IVLINT.class)
    public JAXBElement<IVXBINT> createIVLINTLow(IVXBINT value) {
        return new JAXBElement<IVXBINT>(_IVLTSLow_QNAME, IVXBINT.class, IVLINT.class, value);
    }

    @XmlElementDecl(namespace = "urn:hl7-org:v3", name = "width", scope = IVLINT.class)
    public JAXBElement<INT> createIVLINTWidth(INT value) {
        return new JAXBElement<INT>(_IVLTSWidth_QNAME, INT.class, IVLINT.class, value);
    }

    @XmlElementDecl(namespace = "urn:hl7-org:v3", name = "high", scope = IVLINT.class)
    public JAXBElement<IVXBINT> createIVLINTHigh(IVXBINT value) {
        return new JAXBElement<IVXBINT>(_IVLTSHigh_QNAME, IVXBINT.class, IVLINT.class, value);
    }

    @XmlElementDecl(namespace = "urn:hl7-org:v3", name = "center", scope = IVLINT.class)
    public JAXBElement<INT> createIVLINTCenter(INT value) {
        return new JAXBElement<INT>(_IVLTSCenter_QNAME, INT.class, IVLINT.class, value);
    }

    @XmlElementDecl(namespace = "urn:hl7-org:v3", name = "low", scope = IVLPPDPQ.class)
    public JAXBElement<IVXBPPDPQ> createIVLPPDPQLow(IVXBPPDPQ value) {
        return new JAXBElement<IVXBPPDPQ>(_IVLTSLow_QNAME, IVXBPPDPQ.class, IVLPPDPQ.class, value);
    }

    @XmlElementDecl(namespace = "urn:hl7-org:v3", name = "width", scope = IVLPPDPQ.class)
    public JAXBElement<PPDPQ> createIVLPPDPQWidth(PPDPQ value) {
        return new JAXBElement<PPDPQ>(_IVLTSWidth_QNAME, PPDPQ.class, IVLPPDPQ.class, value);
    }

    @XmlElementDecl(namespace = "urn:hl7-org:v3", name = "high", scope = IVLPPDPQ.class)
    public JAXBElement<IVXBPPDPQ> createIVLPPDPQHigh(IVXBPPDPQ value) {
        return new JAXBElement<IVXBPPDPQ>(_IVLTSHigh_QNAME, IVXBPPDPQ.class, IVLPPDPQ.class, value);
    }

    @XmlElementDecl(namespace = "urn:hl7-org:v3", name = "center", scope = IVLPPDPQ.class)
    public JAXBElement<PPDPQ> createIVLPPDPQCenter(PPDPQ value) {
        return new JAXBElement<PPDPQ>(_IVLTSCenter_QNAME, PPDPQ.class, IVLPPDPQ.class, value);
    }

    @XmlElementDecl(namespace = "urn:hl7-org:v3", name = "low", scope = IVLPPDTS.class)
    public JAXBElement<IVXBPPDTS> createIVLPPDTSLow(IVXBPPDTS value) {
        return new JAXBElement<IVXBPPDTS>(_IVLTSLow_QNAME, IVXBPPDTS.class, IVLPPDTS.class, value);
    }

    @XmlElementDecl(namespace = "urn:hl7-org:v3", name = "width", scope = IVLPPDTS.class)
    public JAXBElement<PPDPQ> createIVLPPDTSWidth(PPDPQ value) {
        return new JAXBElement<PPDPQ>(_IVLTSWidth_QNAME, PPDPQ.class, IVLPPDTS.class, value);
    }

    @XmlElementDecl(namespace = "urn:hl7-org:v3", name = "high", scope = IVLPPDTS.class)
    public JAXBElement<IVXBPPDTS> createIVLPPDTSHigh(IVXBPPDTS value) {
        return new JAXBElement<IVXBPPDTS>(_IVLTSHigh_QNAME, IVXBPPDTS.class, IVLPPDTS.class, value);
    }

    @XmlElementDecl(namespace = "urn:hl7-org:v3", name = "center", scope = IVLPPDTS.class)
    public JAXBElement<PPDTS> createIVLPPDTSCenter(PPDTS value) {
        return new JAXBElement<PPDTS>(_IVLTSCenter_QNAME, PPDTS.class, IVLPPDTS.class, value);
    }
}
