//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2022.01.20 at 04:56:34 PM MSK
//

package com.github.akrtkv.semd_demo.dto.semd;

import javax.xml.bind.annotation.*;
import java.util.ArrayList;
import java.util.List;

@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "POCD_MT000040.Observation", propOrder = {
        "code",
        "effectiveTime",
        "value",
        "reference"
})
public class POCDMT000040Observation {

    @XmlElement(required = true)
    protected Code code;

    protected EffectiveTime effectiveTime;

    protected ANY value;

    protected POCDMT000040Reference reference;

    @XmlAttribute(name = "classCode", required = true)
    protected List<String> classCode;

    @XmlAttribute(name = "moodCode", required = true)
    protected String moodCode;

    public Code getCode() {
        return code;
    }

    public void setCode(Code value) {
        this.code = value;
    }

    public EffectiveTime getEffectiveTime() {
        return effectiveTime;
    }

    public void setEffectiveTime(EffectiveTime value) {
        this.effectiveTime = value;
    }

    public ANY getValue() {
        return value;
    }

    public void setValue(ANY value) {
        this.value = value;
    }

    public POCDMT000040Reference getReference() {
        return reference;
    }

    public void setReference(POCDMT000040Reference value) {
        this.reference = value;
    }

    public List<String> getClassCode() {
        if (classCode == null) {
            classCode = new ArrayList<String>();
        }
        return this.classCode;
    }

    public String getMoodCode() {
        return moodCode;
    }

    public void setMoodCode(String value) {
        this.moodCode = value;
    }

    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class Code
            extends CENonElements {

    }

    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class EffectiveTime
            extends IVLTS {

    }
}
