//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2022.01.20 at 04:56:34 PM MSK
//

package com.github.akrtkv.semd_demo.dto.semd;

import javax.xml.bind.annotation.*;
import java.util.ArrayList;
import java.util.List;

@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "POCD_MT000040.SubstanceAdministration", propOrder = {
        "code",
        "effectiveTime",
        "routeCode",
        "doseQuantity",
        "consumable",
        "entryRelationship",
        "precondition"
})
public class POCDMT000040SubstanceAdministration {

    @XmlElement(required = true)
    protected Code code;

    protected TS effectiveTime;

    @XmlElement(required = true)
    protected RouteCode routeCode;

    protected IVLPQ doseQuantity;

    @XmlElement(required = true)
    protected POCDMT000040Consumable consumable;

    protected List<POCDMT000040EntryRelationship> entryRelationship;

    protected List<POCDMT000040Precondition> precondition;

    @XmlAttribute(name = "classCode", required = true)
    protected List<String> classCode;

    @XmlAttribute(name = "moodCode", required = true)
    protected XDocumentSubstanceMood moodCode;

    public Code getCode() {
        return code;
    }

    public void setCode(Code value) {
        this.code = value;
    }

    public TS getEffectiveTime() {
        return effectiveTime;
    }

    public void setEffectiveTime(TS value) {
        this.effectiveTime = value;
    }

    public RouteCode getRouteCode() {
        return routeCode;
    }

    public void setRouteCode(RouteCode value) {
        this.routeCode = value;
    }

    public IVLPQ getDoseQuantity() {
        return doseQuantity;
    }

    public void setDoseQuantity(IVLPQ value) {
        this.doseQuantity = value;
    }

    public POCDMT000040Consumable getConsumable() {
        return consumable;
    }

    public void setConsumable(POCDMT000040Consumable value) {
        this.consumable = value;
    }

    public List<POCDMT000040EntryRelationship> getEntryRelationship() {
        if (entryRelationship == null) {
            entryRelationship = new ArrayList<POCDMT000040EntryRelationship>();
        }
        return this.entryRelationship;
    }

    public List<POCDMT000040Precondition> getPrecondition() {
        if (precondition == null) {
            precondition = new ArrayList<POCDMT000040Precondition>();
        }
        return this.precondition;
    }

    public List<String> getClassCode() {
        if (classCode == null) {
            classCode = new ArrayList<String>();
        }
        return this.classCode;
    }

    public XDocumentSubstanceMood getMoodCode() {
        return moodCode;
    }

    public void setMoodCode(XDocumentSubstanceMood value) {
        this.moodCode = value;
    }

    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class Code
            extends CENonElements {

    }

    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class RouteCode
            extends CENonElements {

    }
}
