//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2022.01.20 at 04:56:34 PM MSK
//

package com.github.akrtkv.semd_demo.dto.semd;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import java.util.ArrayList;
import java.util.List;

@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "POCD_MT000040.EntryRelationship", propOrder = {
        "substanceAdministration",
        "observation"
})
public class POCDMT000040EntryRelationship {

    protected POCDMT000040SubstanceAdministration1 substanceAdministration;

    protected POCDMT000040Observation observation;

    @XmlAttribute(name = "typeCode", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String typeCode;

    @XmlAttribute(name = "nullFlavor")
    protected List<String> nullFlavor;

    public POCDMT000040SubstanceAdministration1 getSubstanceAdministration() {
        return substanceAdministration;
    }

    public void setSubstanceAdministration(POCDMT000040SubstanceAdministration1 value) {
        this.substanceAdministration = value;
    }

    public POCDMT000040Observation getObservation() {
        return observation;
    }

    public void setObservation(POCDMT000040Observation value) {
        this.observation = value;
    }

    public String getTypeCode() {
        if (typeCode == null) {
            return "COMP";
        } else {
            return typeCode;
        }
    }

    public void setTypeCode(String value) {
        this.typeCode = value;
    }

    public List<String> getNullFlavor() {
        if (nullFlavor == null) {
            nullFlavor = new ArrayList<String>();
        }
        return this.nullFlavor;
    }
}
