//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2022.01.20 at 04:56:34 PM MSK
//

package com.github.akrtkv.semd_demo.dto.semd;

import javax.xml.bind.annotation.*;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import java.util.ArrayList;
import java.util.List;

@XmlRootElement(name = "ClinicalDocument")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "POCD_MT000040.ClinicalDocument", propOrder = {
        "realmCode",
        "typeId",
        "templateId",
        "id",
        "code",
        "title",
        "effectiveTime",
        "confidentialityCode",
        "languageCode",
        "setId",
        "versionNumber",
        "recordTarget",
        "author",
        "custodian",
        "informationRecipient",
        "legalAuthenticator",
        "documentationOf",
        "componentOf",
        "component"
})
public class POCDMT000040ClinicalDocument {

    @XmlElement(required = true)
    protected RealmCode realmCode;

    @XmlElement(required = true)
    protected TypeId typeId;

    @XmlElement(required = true)
    protected TemplateId templateId;

    @XmlElement(required = true)
    protected Id id;

    @XmlElement(required = true)
    protected Code code;

    @XmlElement(required = true)
    protected String title;

    @XmlElement(required = true)
    protected EffectiveTime effectiveTime;

    @XmlElement(required = true)
    protected ConfidentialityCode confidentialityCode;

    @XmlElement(required = true)
    protected LanguageCode languageCode;

    @XmlElement(required = true)
    protected SetId setId;

    @XmlElement(required = true)
    protected VersionNumber versionNumber;

    @XmlElement(required = true)
    protected POCDMT000040RecordTarget recordTarget;

    @XmlElement(required = true)
    protected POCDMT000040Author author;

    @XmlElement(required = true)
    protected POCDMT000040Custodian custodian;

    @XmlElement(required = true)
    protected List<POCDMT000040InformationRecipient> informationRecipient;

    @XmlElement(required = true)
    protected POCDMT000040LegalAuthenticator legalAuthenticator;

    protected POCDMT000040DocumentationOf documentationOf;

    protected POCDMT000040Component1 componentOf;

    @XmlElement(required = true)
    protected POCDMT000040Component2 component;

    public RealmCode getRealmCode() {
        return realmCode;
    }

    public void setRealmCode(RealmCode value) {
        this.realmCode = value;
    }

    public TypeId getTypeId() {
        return typeId;
    }

    public void setTypeId(TypeId value) {
        this.typeId = value;
    }

    public TemplateId getTemplateId() {
        return templateId;
    }

    public void setTemplateId(TemplateId value) {
        this.templateId = value;
    }

    public Id getId() {
        return id;
    }

    public void setId(Id value) {
        this.id = value;
    }

    public Code getCode() {
        return code;
    }

    public void setCode(Code value) {
        this.code = value;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String value) {
        this.title = value;
    }

    public EffectiveTime getEffectiveTime() {
        return effectiveTime;
    }

    public void setEffectiveTime(EffectiveTime value) {
        this.effectiveTime = value;
    }

    public ConfidentialityCode getConfidentialityCode() {
        return confidentialityCode;
    }

    public void setConfidentialityCode(ConfidentialityCode value) {
        this.confidentialityCode = value;
    }

    public LanguageCode getLanguageCode() {
        return languageCode;
    }

    public void setLanguageCode(LanguageCode value) {
        this.languageCode = value;
    }

    public SetId getSetId() {
        return setId;
    }

    public void setSetId(SetId value) {
        this.setId = value;
    }

    public VersionNumber getVersionNumber() {
        return versionNumber;
    }

    public void setVersionNumber(VersionNumber value) {
        this.versionNumber = value;
    }

    public POCDMT000040RecordTarget getRecordTarget() {
        return recordTarget;
    }

    public void setRecordTarget(POCDMT000040RecordTarget value) {
        this.recordTarget = value;
    }

    public POCDMT000040Author getAuthor() {
        return author;
    }

    public void setAuthor(POCDMT000040Author value) {
        this.author = value;
    }

    public POCDMT000040Custodian getCustodian() {
        return custodian;
    }

    public void setCustodian(POCDMT000040Custodian value) {
        this.custodian = value;
    }

    public List<POCDMT000040InformationRecipient> getInformationRecipient() {
        if (informationRecipient == null) {
            informationRecipient = new ArrayList<POCDMT000040InformationRecipient>();
        }
        return this.informationRecipient;
    }

    public POCDMT000040LegalAuthenticator getLegalAuthenticator() {
        return legalAuthenticator;
    }

    public void setLegalAuthenticator(POCDMT000040LegalAuthenticator value) {
        this.legalAuthenticator = value;
    }

    public POCDMT000040DocumentationOf getDocumentationOf() {
        return documentationOf;
    }

    public void setDocumentationOf(POCDMT000040DocumentationOf value) {
        this.documentationOf = value;
    }

    public POCDMT000040Component1 getComponentOf() {
        return componentOf;
    }

    public void setComponentOf(POCDMT000040Component1 value) {
        this.componentOf = value;
    }

    public POCDMT000040Component2 getComponent() {
        return component;
    }

    public void setComponent(POCDMT000040Component2 value) {
        this.component = value;
    }

    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class Code
            extends CENonElements {

    }

    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class ConfidentialityCode
            extends CENonElements {

    }

    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class EffectiveTime
            extends TS {

    }

    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class Id
            extends II {

    }

    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class LanguageCode {

        @XmlAttribute(name = "code", required = true)
        @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
        protected String code;

        public String getCode() {
            if (code == null) {
                return "ru-RU";
            } else {
                return code;
            }
        }

        public void setCode(String value) {
            this.code = value;
        }
    }

    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class RealmCode {

        @XmlAttribute(name = "code", required = true)
        @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
        protected String code;

        public String getCode() {
            if (code == null) {
                return "RU";
            } else {
                return code;
            }
        }

        public void setCode(String value) {
            this.code = value;
        }
    }

    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class SetId
            extends II {

    }

    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class TemplateId
            extends II {

    }

    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class TypeId
            extends II {

    }

    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class VersionNumber
            extends INT {

    }
}
