//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2022.01.20 at 04:56:34 PM MSK
//

package com.github.akrtkv.semd_demo.dto.semd;

import javax.xml.bind.annotation.*;
import java.util.ArrayList;
import java.util.List;

@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "POCD_MT000040.Act", propOrder = {
        "code",
        "text",
        "effectiveTime",
        "entryRelationship",
        "reference"
})
public class POCDMT000040Act {

    @XmlElement(required = true)
    protected Code code;

    @XmlElement(required = true)
    protected ED text;

    @XmlElement(required = true)
    protected TS effectiveTime;

    protected List<POCDMT000040EntryRelationship> entryRelationship;

    @XmlElement(required = true)
    protected POCDMT000040Reference reference;

    @XmlAttribute(name = "classCode", required = true)
    protected XActClassDocumentEntryAct classCode;

    @XmlAttribute(name = "moodCode", required = true)
    protected XDocumentActMood moodCode;

    public Code getCode() {
        return code;
    }

    public void setCode(Code value) {
        this.code = value;
    }

    public ED getText() {
        return text;
    }

    public void setText(ED value) {
        this.text = value;
    }

    public TS getEffectiveTime() {
        return effectiveTime;
    }

    public void setEffectiveTime(TS value) {
        this.effectiveTime = value;
    }

    public List<POCDMT000040EntryRelationship> getEntryRelationship() {
        if (entryRelationship == null) {
            entryRelationship = new ArrayList<POCDMT000040EntryRelationship>();
        }
        return this.entryRelationship;
    }

    public POCDMT000040Reference getReference() {
        return reference;
    }

    public void setReference(POCDMT000040Reference value) {
        this.reference = value;
    }

    public XActClassDocumentEntryAct getClassCode() {
        if (classCode == null) {
            return XActClassDocumentEntryAct.ACT;
        } else {
            return classCode;
        }
    }

    public void setClassCode(XActClassDocumentEntryAct value) {
        this.classCode = value;
    }

    public XDocumentActMood getMoodCode() {
        if (moodCode == null) {
            return XDocumentActMood.EVN;
        } else {
            return moodCode;
        }
    }

    public void setMoodCode(XDocumentActMood value) {
        this.moodCode = value;
    }

    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class Code
            extends CENonElements {

    }
}
