//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2022.01.20 at 04:56:34 PM MSK
//

package com.github.akrtkv.semd_demo.dto.semd;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "POCD_MT000040.Patient", propOrder = {
        "name",
        "administrativeGenderCode",
        "birthTime"
})
public class POCDMT000040Patient {

    @XmlElement(required = true)
    protected PN name;

    @XmlElement(required = true)
    protected AdministrativeGenderCode administrativeGenderCode;

    @XmlElement(required = true)
    protected TS birthTime;

    public PN getName() {
        return name;
    }

    public void setName(PN value) {
        this.name = value;
    }

    public AdministrativeGenderCode getAdministrativeGenderCode() {
        return administrativeGenderCode;
    }

    public void setAdministrativeGenderCode(AdministrativeGenderCode value) {
        this.administrativeGenderCode = value;
    }

    public TS getBirthTime() {
        return birthTime;
    }

    public void setBirthTime(TS value) {
        this.birthTime = value;
    }

    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class AdministrativeGenderCode
            extends CENonElements {

    }
}
