//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2022.01.20 at 04:56:34 PM MSK
//

package com.github.akrtkv.semd_demo.dto.semd;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;
import java.util.ArrayList;
import java.util.List;

@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "POCD_MT000040.Component1", propOrder = {
        "encompassingEncounter"
})
public class POCDMT000040Component1 {

    protected POCDMT000040EncompassingEncounter encompassingEncounter;

    @XmlAttribute(name = "nullFlavor")
    protected List<String> nullFlavor;

    public POCDMT000040EncompassingEncounter getEncompassingEncounter() {
        return encompassingEncounter;
    }

    public void setEncompassingEncounter(POCDMT000040EncompassingEncounter value) {
        this.encompassingEncounter = value;
    }

    public List<String> getNullFlavor() {
        if (nullFlavor == null) {
            nullFlavor = new ArrayList<String>();
        }
        return this.nullFlavor;
    }
}
