//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2022.01.20 at 04:56:34 PM MSK
//

package com.github.akrtkv.semd_demo.dto.semd;

import javax.xml.bind.annotation.*;
import java.util.ArrayList;
import java.util.List;

@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "POCD_MT000040.LegalAuthenticator", propOrder = {
        "time",
        "signatureCode",
        "assignedEntity"
})
public class POCDMT000040LegalAuthenticator {

    @XmlElement(required = true)
    protected POCDMT000040Time time;

    @XmlElement(required = true)
    protected SignatureCode signatureCode;

    @XmlElement(required = true)
    protected POCDMT000040AssignedEntityLegalAuthenticator assignedEntity;

    public POCDMT000040Time getTime() {
        return time;
    }

    public void setTime(POCDMT000040Time value) {
        this.time = value;
    }

    public SignatureCode getSignatureCode() {
        return signatureCode;
    }

    public void setSignatureCode(SignatureCode value) {
        this.signatureCode = value;
    }

    public POCDMT000040AssignedEntityLegalAuthenticator getAssignedEntity() {
        return assignedEntity;
    }

    public void setAssignedEntity(POCDMT000040AssignedEntityLegalAuthenticator value) {
        this.assignedEntity = value;
    }

    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class SignatureCode {

        @XmlAttribute(name = "nullFlavor", required = true)
        protected List<String> nullFlavor;

        public List<String> getNullFlavor() {
            if (nullFlavor == null) {
                nullFlavor = new ArrayList<String>();
            }
            return this.nullFlavor;
        }
    }
}
