//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2022.01.20 at 04:56:34 PM MSK
//

package com.github.akrtkv.semd_demo.dto.semd;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;
import java.util.ArrayList;
import java.util.List;

@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "POCD_MT000040.ExternalDocument", propOrder = {
        "id"
})
public class POCDMT000040ExternalDocument {

    protected Id id;

    @XmlAttribute(name = "classCode")
    protected String classCode;

    @XmlAttribute(name = "moodCode")
    protected List<String> moodCode;

    @XmlAttribute(name = "nullFlavor")
    protected List<String> nullFlavor;

    public Id getId() {
        return id;
    }

    public void setId(Id value) {
        this.id = value;
    }

    public String getClassCode() {
        return classCode;
    }

    public void setClassCode(String value) {
        this.classCode = value;
    }

    public List<String> getMoodCode() {
        if (moodCode == null) {
            moodCode = new ArrayList<String>();
        }
        return this.moodCode;
    }

    public List<String> getNullFlavor() {
        if (nullFlavor == null) {
            nullFlavor = new ArrayList<String>();
        }
        return this.nullFlavor;
    }

    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class Id
            extends II {

    }
}
