//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2022.01.20 at 04:56:34 PM MSK
//

package com.github.akrtkv.semd_demo.dto.semd;

import com.github.akrtkv.semd_demo.dto.semd.fias.FiasAddress;

import javax.xml.bind.annotation.*;
import java.util.ArrayList;
import java.util.List;

@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "POCD_MT000040.AssignedAuthor", propOrder = {
        "id",
        "code",
        "addr",
        "telecom",
        "assignedPerson",
        "representedOrganization"
})
public class POCDMT000040AssignedAuthor {

    @XmlElement(required = true)
    protected List<IIId> id;

    @XmlElement(required = true)
    protected POCDMT000040CodeProfession code;

    protected Addr addr;

    protected List<TEL> telecom;

    @XmlElement(required = true)
    protected POCDMT000040Person assignedPerson;

    @XmlElement(required = true)
    protected RepresentedOrganization representedOrganization;

    public List<IIId> getId() {
        if (id == null) {
            id = new ArrayList<IIId>();
        }
        return this.id;
    }

    public POCDMT000040CodeProfession getCode() {
        return code;
    }

    public void setCode(POCDMT000040CodeProfession value) {
        this.code = value;
    }

    public Addr getAddr() {
        return addr;
    }

    public void setAddr(Addr value) {
        this.addr = value;
    }

    public List<TEL> getTelecom() {
        if (telecom == null) {
            telecom = new ArrayList<TEL>();
        }
        return this.telecom;
    }

    public POCDMT000040Person getAssignedPerson() {
        return assignedPerson;
    }

    public void setAssignedPerson(POCDMT000040Person value) {
        this.assignedPerson = value;
    }

    public RepresentedOrganization getRepresentedOrganization() {
        return representedOrganization;
    }

    public void setRepresentedOrganization(RepresentedOrganization value) {
        this.representedOrganization = value;
    }

    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
            "streetAddressLine",
            "stateCode",
            "postalCode",
            "address"
    })
    public static class Addr {

        protected String streetAddressLine;

        @XmlElement(namespace = "urn:hl7-ru:address")
        protected CDAddressStateCode stateCode;

        protected AdxpPostalCode postalCode;

        @XmlElement(name = "Address", namespace = "urn:hl7-ru:fias")
        protected FiasAddress address;

        @XmlAttribute(name = "use")
        protected List<String> use;

        @XmlAttribute(name = "nullFlavor")
        protected List<String> nullFlavor;

        public String getStreetAddressLine() {
            return streetAddressLine;
        }

        public void setStreetAddressLine(String value) {
            this.streetAddressLine = value;
        }

        public CDAddressStateCode getStateCode() {
            return stateCode;
        }

        public void setStateCode(CDAddressStateCode value) {
            this.stateCode = value;
        }

        public AdxpPostalCode getPostalCode() {
            return postalCode;
        }

        public void setPostalCode(AdxpPostalCode value) {
            this.postalCode = value;
        }

        public FiasAddress getAddress() {
            return address;
        }

        public void setAddress(FiasAddress value) {
            this.address = value;
        }

        public List<String> getUse() {
            if (use == null) {
                use = new ArrayList<String>();
            }
            return this.use;
        }

        public List<String> getNullFlavor() {
            if (nullFlavor == null) {
                nullFlavor = new ArrayList<String>();
            }
            return this.nullFlavor;
        }
    }

    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
            "id",
            "name",
            "telecom",
            "addr"
    })
    public static class RepresentedOrganization {

        protected IIIdOrgNonNF id;

        protected String name;

        protected List<TEL> telecom;

        protected POCDMT000040AssignedEntityLegalAuthenticator.RepresentedOrganization.Addr addr;

        @XmlAttribute(name = "classCode", required = true)
        protected String classCode;

        @XmlAttribute(name = "nullFlavor")
        protected List<String> nullFlavor;

        public IIIdOrgNonNF getId() {
            return id;
        }

        public void setId(IIIdOrgNonNF value) {
            this.id = value;
        }

        public String getName() {
            return name;
        }

        public void setName(String value) {
            this.name = value;
        }

        public List<TEL> getTelecom() {
            if (telecom == null) {
                telecom = new ArrayList<TEL>();
            }
            return this.telecom;
        }

        public POCDMT000040AssignedEntityLegalAuthenticator.RepresentedOrganization.Addr getAddr() {
            return addr;
        }

        public void setAddr(POCDMT000040AssignedEntityLegalAuthenticator.RepresentedOrganization.Addr value) {
            this.addr = value;
        }

        public String getClassCode() {
            if (classCode == null) {
                return "ORG";
            } else {
                return classCode;
            }
        }

        public void setClassCode(String value) {
            this.classCode = value;
        }

        public List<String> getNullFlavor() {
            if (nullFlavor == null) {
                nullFlavor = new ArrayList<String>();
            }
            return this.nullFlavor;
        }
    }
}
