//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2022.01.20 at 04:56:34 PM MSK
//

package com.github.akrtkv.semd_demo.dto.semd;

import javax.xml.bind.annotation.*;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;

@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "POCD_MT000040.Product", propOrder = {
        "manufacturedProduct"
})
public class POCDMT000040Product {

    @XmlElement(required = true)
    protected POCDMT000040ManufacturedProduct manufacturedProduct;

    @XmlAttribute(name = "typeCode")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String typeCode;

    public POCDMT000040ManufacturedProduct getManufacturedProduct() {
        return manufacturedProduct;
    }

    public void setManufacturedProduct(POCDMT000040ManufacturedProduct value) {
        this.manufacturedProduct = value;
    }

    public String getTypeCode() {
        if (typeCode == null) {
            return "PRD";
        } else {
            return typeCode;
        }
    }

    public void setTypeCode(String value) {
        this.typeCode = value;
    }
}
