//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2022.01.20 at 04:56:34 PM MSK
//

package com.github.akrtkv.semd_demo.dto.semd;

import javax.xml.bind.annotation.*;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import java.util.ArrayList;
import java.util.List;

@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "POCD_MT000040.Precondition", propOrder = {
        "criterion"
})
public class POCDMT000040Precondition {

    @XmlElement(required = true)
    protected POCDMT000040Criterion criterion;

    @XmlAttribute(name = "typeCode", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String typeCode;

    @XmlAttribute(name = "nullFlavor")
    protected List<String> nullFlavor;

    public POCDMT000040Criterion getCriterion() {
        return criterion;
    }

    public void setCriterion(POCDMT000040Criterion value) {
        this.criterion = value;
    }

    public String getTypeCode() {
        return typeCode;
    }

    public void setTypeCode(String value) {
        this.typeCode = value;
    }

    public List<String> getNullFlavor() {
        if (nullFlavor == null) {
            nullFlavor = new ArrayList<String>();
        }
        return this.nullFlavor;
    }
}
