//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2022.01.20 at 04:56:34 PM MSK
//

package com.github.akrtkv.semd_demo.dto.semd;

import javax.xml.bind.annotation.*;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;

@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "POCD_MT000040.ManufacturedProduct", propOrder = {
        "manufacturedMaterial"
})
public class POCDMT000040ManufacturedProduct {

    @XmlElement(required = true)
    protected POCDMT000040Material manufacturedMaterial;

    @XmlAttribute(name = "classCode")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String classCode;

    public POCDMT000040Material getManufacturedMaterial() {
        return manufacturedMaterial;
    }

    public void setManufacturedMaterial(POCDMT000040Material value) {
        this.manufacturedMaterial = value;
    }

    public String getClassCode() {
        return classCode;
    }

    public void setClassCode(String value) {
        this.classCode = value;
    }
}
