//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2022.01.20 at 04:56:34 PM MSK
//

package com.github.akrtkv.semd_demo.dto.semd;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;

@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "POCD_MT000040.Entry", propOrder = {
        "observation",
        "substanceAdministration",
        "supply",
        "act"
})
public class POCDMT000040Entry {

    protected POCDMT000040Observation observation;

    protected POCDMT000040SubstanceAdministration substanceAdministration;

    protected POCDMT000040Supply supply;

    protected POCDMT000040Act act;

    public POCDMT000040Observation getObservation() {
        return observation;
    }

    public void setObservation(POCDMT000040Observation value) {
        this.observation = value;
    }

    public POCDMT000040SubstanceAdministration getSubstanceAdministration() {
        return substanceAdministration;
    }

    public void setSubstanceAdministration(POCDMT000040SubstanceAdministration value) {
        this.substanceAdministration = value;
    }

    public POCDMT000040Supply getSupply() {
        return supply;
    }

    public void setSupply(POCDMT000040Supply value) {
        this.supply = value;
    }

    public POCDMT000040Act getAct() {
        return act;
    }

    public void setAct(POCDMT000040Act value) {
        this.act = value;
    }
}
