//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2022.01.20 at 04:56:34 PM MSK
//

package com.github.akrtkv.semd_demo.dto.semd;

import com.github.akrtkv.semd_demo.dto.semd.identity.POCDMT000040IdentityDoc;
import com.github.akrtkv.semd_demo.dto.semd.identity.POCDMT000040InsurancePolicy;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import java.util.ArrayList;
import java.util.List;

@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "POCD_MT000040.PatientRole", propOrder = {
        "id",
        "identityDoc",
        "insurancePolicy",
        "addr",
        "telecom",
        "patient",
        "providerOrganization"
})
public class POCDMT000040PatientRole {

    @XmlElement(required = true)
    protected List<IIIdPatient> id;

    @XmlElement(name = "IdentityDoc", namespace = "urn:hl7-ru:identity", required = true)
    protected POCDMT000040IdentityDoc identityDoc;

    @XmlElement(name = "InsurancePolicy", namespace = "urn:hl7-ru:identity", required = true)
    protected POCDMT000040InsurancePolicy insurancePolicy;

    @XmlElement(required = true)
    protected List<ADPatient> addr;

    protected List<TEL> telecom;

    @XmlElement(required = true)
    protected POCDMT000040Patient patient;

    @XmlElement(required = true)
    protected POCDMT000040OrganizationPatient providerOrganization;

    public List<IIIdPatient> getId() {
        if (id == null) {
            id = new ArrayList<IIIdPatient>();
        }
        return this.id;
    }

    public POCDMT000040IdentityDoc getIdentityDoc() {
        return identityDoc;
    }

    public void setIdentityDoc(POCDMT000040IdentityDoc value) {
        this.identityDoc = value;
    }

    public POCDMT000040InsurancePolicy getInsurancePolicy() {
        return insurancePolicy;
    }

    public void setInsurancePolicy(POCDMT000040InsurancePolicy value) {
        this.insurancePolicy = value;
    }

    public List<ADPatient> getAddr() {
        if (addr == null) {
            addr = new ArrayList<ADPatient>();
        }
        return this.addr;
    }

    public List<TEL> getTelecom() {
        if (telecom == null) {
            telecom = new ArrayList<TEL>();
        }
        return this.telecom;
    }

    public POCDMT000040Patient getPatient() {
        return patient;
    }

    public void setPatient(POCDMT000040Patient value) {
        this.patient = value;
    }

    public POCDMT000040OrganizationPatient getProviderOrganization() {
        return providerOrganization;
    }

    public void setProviderOrganization(POCDMT000040OrganizationPatient value) {
        this.providerOrganization = value;
    }
}
