//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2022.01.20 at 04:56:34 PM MSK
//

package com.github.akrtkv.semd_demo.dto.semd;

import javax.xml.bind.annotation.*;

@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "POCD_MT000040.Supply", propOrder = {
        "code",
        "text",
        "quantity",
        "product"
})
public class POCDMT000040Supply {

    @XmlElement(required = true)
    protected Code code;

    @XmlElement(required = true)
    protected String text;

    @XmlElement(required = true)
    protected PQ quantity;

    @XmlElement(required = true)
    protected POCDMT000040Product product;

    @XmlAttribute(name = "classCode", required = true)
    protected ActClassSupply classCode;

    @XmlAttribute(name = "moodCode", required = true)
    protected XDocumentSubstanceMood moodCode;

    public Code getCode() {
        return code;
    }

    public void setCode(Code value) {
        this.code = value;
    }

    public String getText() {
        return text;
    }

    public void setText(String value) {
        this.text = value;
    }

    public PQ getQuantity() {
        return quantity;
    }

    public void setQuantity(PQ value) {
        this.quantity = value;
    }

    public POCDMT000040Product getProduct() {
        return product;
    }

    public void setProduct(POCDMT000040Product value) {
        this.product = value;
    }

    public ActClassSupply getClassCode() {
        if (classCode == null) {
            return ActClassSupply.SPLY;
        } else {
            return classCode;
        }
    }

    public void setClassCode(ActClassSupply value) {
        this.classCode = value;
    }

    public XDocumentSubstanceMood getMoodCode() {
        if (moodCode == null) {
            return XDocumentSubstanceMood.RQO;
        } else {
            return moodCode;
        }
    }

    public void setMoodCode(XDocumentSubstanceMood value) {
        this.moodCode = value;
    }

    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class Code
            extends CENonElements {

    }
}
