//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2022.01.20 at 04:56:34 PM MSK
//

package com.github.akrtkv.semd_demo.dto.semd;

import javax.xml.bind.annotation.*;

@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PPD_TS", propOrder = {
        "standardDeviation"
})
@XmlSeeAlso({
        IVXBPPDTS.class,
        SXCMPPDTS.class
})
public class PPDTS
        extends TS {

    protected PQ standardDeviation;

    @XmlAttribute(name = "distributionType")
    protected ProbabilityDistributionType distributionType;

    public PQ getStandardDeviation() {
        return standardDeviation;
    }

    public void setStandardDeviation(PQ value) {
        this.standardDeviation = value;
    }

    public ProbabilityDistributionType getDistributionType() {
        return distributionType;
    }

    public void setDistributionType(ProbabilityDistributionType value) {
        this.distributionType = value;
    }
}
