//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2022.01.20 at 04:56:34 PM MSK
//

package com.github.akrtkv.semd_demo.dto.semd;

import javax.xml.bind.annotation.*;

@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RTO_QTY_QTY", propOrder = {
        "numerator",
        "denominator"
})
@XmlSeeAlso({
        RTO.class
})
public class RTOQTYQTY
        extends QTY {

    @XmlElement(required = true)
    protected QTY numerator;

    @XmlElement(required = true)
    protected QTY denominator;

    public QTY getNumerator() {
        return numerator;
    }

    public void setNumerator(QTY value) {
        this.numerator = value;
    }

    public QTY getDenominator() {
        return denominator;
    }

    public void setDenominator(QTY value) {
        this.denominator = value;
    }
}
