//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2022.01.20 at 04:56:34 PM MSK
//

package com.github.akrtkv.semd_demo.dto.semd;

import javax.xml.bind.annotation.*;
import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;

@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SLIST_TS", propOrder = {
        "origin",
        "scale",
        "digits"
})
public class SLISTTS
        extends ANY {

    @XmlElement(required = true)
    protected TS origin;

    @XmlElement(required = true)
    protected PQ scale;

    @XmlList
    @XmlElement(required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected List<BigInteger> digits;

    public TS getOrigin() {
        return origin;
    }

    public void setOrigin(TS value) {
        this.origin = value;
    }

    public PQ getScale() {
        return scale;
    }

    public void setScale(PQ value) {
        this.scale = value;
    }

    public List<BigInteger> getDigits() {
        if (digits == null) {
            digits = new ArrayList<BigInteger>();
        }
        return this.digits;
    }
}
