//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2022.01.20 at 04:56:34 PM MSK
//

package com.github.akrtkv.semd_demo.dto.semd;

import javax.xml.bind.annotation.*;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import java.util.ArrayList;
import java.util.List;

@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "StrucDoc.List", propOrder = {
        "caption",
        "item"
})
public class StrucDocList {

    protected StrucDocCaption caption;

    @XmlElement(required = true)
    protected List<StrucDocItem> item;

    @XmlAttribute(name = "ID")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    @XmlSchemaType(name = "ID")
    protected String id;

    @XmlAttribute(name = "language")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NMTOKEN")
    protected String language;

    @XmlAttribute(name = "styleCode")
    @XmlSchemaType(name = "NMTOKENS")
    protected List<String> styleCode;

    @XmlAttribute(name = "listType")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String listType;

    public StrucDocCaption getCaption() {
        return caption;
    }

    public void setCaption(StrucDocCaption value) {
        this.caption = value;
    }

    public List<StrucDocItem> getItem() {
        if (item == null) {
            item = new ArrayList<StrucDocItem>();
        }
        return this.item;
    }

    public String getID() {
        return id;
    }

    public void setID(String value) {
        this.id = value;
    }

    public String getLanguage() {
        return language;
    }

    public void setLanguage(String value) {
        this.language = value;
    }

    public List<String> getStyleCode() {
        if (styleCode == null) {
            styleCode = new ArrayList<String>();
        }
        return this.styleCode;
    }

    public String getListType() {
        if (listType == null) {
            return "unordered";
        } else {
            return listType;
        }
    }

    public void setListType(String value) {
        this.listType = value;
    }
}
