//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2022.01.20 at 04:56:34 PM MSK
//

package com.github.akrtkv.semd_demo.dto.semd.identity;

import su.medsoft.rir.recipe.dto.iemk_new_edition.IVXBTS;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;
import java.util.ArrayList;
import java.util.List;

@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Effective_time", propOrder = {
        "low",
        "high"
})
public class EffectiveTime {

    protected Low low;

    protected High high;

    @XmlAttribute(name = "nullFlavor")
    protected List<String> nullFlavor;

    public Low getLow() {
        return low;
    }

    public void setLow(Low value) {
        this.low = value;
    }

    public High getHigh() {
        return high;
    }

    public void setHigh(High value) {
        this.high = value;
    }

    public List<String> getNullFlavor() {
        if (nullFlavor == null) {
            nullFlavor = new ArrayList<String>();
        }
        return this.nullFlavor;
    }

    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class High
            extends IVXBTS {

    }

    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class Low
            extends IVXBTS {

    }
}
