//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2022.01.20 at 04:56:34 PM MSK
//

@javax.xml.bind.annotation.XmlSchema(namespace = "urn:hl7-ru:identity", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.github.akrtkv.semd_demo.dto.semd.identity;
