//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2022.01.20 at 04:56:34 PM MSK
//

package com.github.akrtkv.semd_demo.dto.semd.identity;

import su.medsoft.rir.recipe.dto.iemk_new_edition.CENonElements;
import su.medsoft.rir.recipe.dto.iemk_new_edition.ST;
import su.medsoft.rir.recipe.dto.iemk_new_edition.STST;

import javax.xml.bind.annotation.*;
import java.util.ArrayList;
import java.util.List;

@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "POCD_MT000040.DocInfo", propOrder = {
        "identityDocType",
        "insurancePolicyType",
        "series",
        "number",
        "inn",
        "effectiveTime"
})
public class POCDMT000040DocInfo {

    @XmlElement(name = "IdentityDocType")
    protected IdentityDocType identityDocType;

    @XmlElement(name = "InsurancePolicyType")
    protected InsurancePolicyType insurancePolicyType;

    @XmlElement(name = "Series")
    protected Series series;

    @XmlElement(name = "Number")
    protected Number number;

    @XmlElement(name = "INN")
    protected ST inn;

    protected EffectiveTime effectiveTime;

    @XmlAttribute(name = "nullFlavor")
    protected List<String> nullFlavor;

    public IdentityDocType getIdentityDocType() {
        return identityDocType;
    }

    public void setIdentityDocType(IdentityDocType value) {
        this.identityDocType = value;
    }

    public InsurancePolicyType getInsurancePolicyType() {
        return insurancePolicyType;
    }

    public void setInsurancePolicyType(InsurancePolicyType value) {
        this.insurancePolicyType = value;
    }

    public Series getSeries() {
        return series;
    }

    public void setSeries(Series value) {
        this.series = value;
    }

    public Number getNumber() {
        return number;
    }

    public void setNumber(Number value) {
        this.number = value;
    }

    public ST getINN() {
        return inn;
    }

    public void setINN(ST value) {
        this.inn = value;
    }

    public EffectiveTime getEffectiveTime() {
        return effectiveTime;
    }

    public void setEffectiveTime(EffectiveTime value) {
        this.effectiveTime = value;
    }

    public List<String> getNullFlavor() {
        if (nullFlavor == null) {
            nullFlavor = new ArrayList<String>();
        }
        return this.nullFlavor;
    }

    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class IdentityDocType
            extends CENonElements {

    }

    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class InsurancePolicyType
            extends CENonElements {

    }

    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class Number
            extends STST {

        @XmlAttribute(name = "nullFlavor")
        protected List<String> nullFlavor;

        public List<String> getNullFlavor() {
            if (nullFlavor == null) {
                nullFlavor = new ArrayList<String>();
            }
            return this.nullFlavor;
        }
    }

    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class Series
            extends STST {

        @XmlAttribute(name = "nullFlavor")
        protected List<String> nullFlavor;

        public List<String> getNullFlavor() {
            if (nullFlavor == null) {
                nullFlavor = new ArrayList<String>();
            }
            return this.nullFlavor;
        }
    }
}
