//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2022.01.20 at 04:56:34 PM MSK
//

package com.github.akrtkv.semd_demo.dto.semd.identity;

import com.github.akrtkv.semd_demo.dto.semd.CENonElements;
import com.github.akrtkv.semd_demo.dto.semd.TS;

import javax.xml.bind.annotation.*;
import java.util.ArrayList;
import java.util.List;

@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "POCD_MT000040.IdentityDoc", propOrder = {
        "identityCardType",
        "series",
        "number",
        "issueOrgName",
        "issueOrgCode",
        "issueDate"
})
public class POCDMT000040IdentityDoc {

    @XmlElement(name = "IdentityCardType")
    protected IdentityCardType identityCardType;

    @XmlElement(name = "Series")
    protected String series;

    @XmlElement(name = "Number")
    protected String number;

    @XmlElement(name = "IssueOrgName")
    protected String issueOrgName;

    @XmlElement(name = "IssueOrgCode")
    protected String issueOrgCode;

    @XmlElement(name = "IssueDate")
    protected IssueDate issueDate;

    @XmlAttribute(name = "nullFlavor")
    protected List<String> nullFlavor;

    public IdentityCardType getIdentityCardType() {
        return identityCardType;
    }

    public void setIdentityCardType(IdentityCardType value) {
        this.identityCardType = value;
    }

    public String getSeries() {
        return series;
    }

    public void setSeries(String value) {
        this.series = value;
    }

    public String getNumber() {
        return number;
    }

    public void setNumber(String value) {
        this.number = value;
    }

    public String getIssueOrgName() {
        return issueOrgName;
    }

    public void setIssueOrgName(String value) {
        this.issueOrgName = value;
    }

    public String getIssueOrgCode() {
        return issueOrgCode;
    }

    public void setIssueOrgCode(String value) {
        this.issueOrgCode = value;
    }

    public IssueDate getIssueDate() {
        return issueDate;
    }

    public void setIssueDate(IssueDate value) {
        this.issueDate = value;
    }

    public List<String> getNullFlavor() {
        if (nullFlavor == null) {
            nullFlavor = new ArrayList<String>();
        }
        return this.nullFlavor;
    }

    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class IdentityCardType
            extends CENonElements {

    }

    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class IssueDate
            extends TS {

    }
}
