//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2022.01.20 at 04:56:34 PM MSK
//

package com.github.akrtkv.semd_demo.dto.semd.identity;

import su.medsoft.rir.recipe.dto.iemk_new_edition.ST;

import javax.xml.bind.annotation.*;
import java.util.ArrayList;
import java.util.List;

@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "POCD_MT000040.Props", propOrder = {
        "ogrn",
        "ogrnip",
        "okpo",
        "okato"
})
public class POCDMT000040Props {

    @XmlElement(name = "Ogrn")
    protected String ogrn;

    @XmlElement(name = "Ogrnip")
    protected ST ogrnip;

    @XmlElement(name = "Okpo")
    protected String okpo;

    @XmlElement(name = "Okato")
    protected String okato;

    @XmlAttribute(name = "nullFlavor")
    protected List<String> nullFlavor;

    public String getOgrn() {
        return ogrn;
    }

    public void setOgrn(String value) {
        this.ogrn = value;
    }

    public ST getOgrnip() {
        return ogrnip;
    }

    public void setOgrnip(ST value) {
        this.ogrnip = value;
    }

    public String getOkpo() {
        return okpo;
    }

    public void setOkpo(String value) {
        this.okpo = value;
    }

    public String getOkato() {
        return okato;
    }

    public void setOkato(String value) {
        this.okato = value;
    }

    public List<String> getNullFlavor() {
        if (nullFlavor == null) {
            nullFlavor = new ArrayList<String>();
        }
        return this.nullFlavor;
    }
}
