//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2022.01.20 at 04:56:34 PM MSK
//

package com.github.akrtkv.semd_demo.dto.semd.fias;

import javax.xml.bind.annotation.*;
import java.util.ArrayList;
import java.util.List;

@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FiasAddress", propOrder = {
        "aoguid",
        "houseguid"
})
public class FiasAddress {

    @XmlElement(name = "AOGUID")
    protected String aoguid;

    @XmlElement(name = "HOUSEGUID")
    protected String houseguid;

    @XmlAttribute(name = "nullFlavor")
    protected List<String> nullFlavor;

    public String getAOGUID() {
        return aoguid;
    }

    public void setAOGUID(String value) {
        this.aoguid = value;
    }

    public String getHOUSEGUID() {
        return houseguid;
    }

    public void setHOUSEGUID(String value) {
        this.houseguid = value;
    }

    public List<String> getNullFlavor() {
        if (nullFlavor == null) {
            nullFlavor = new ArrayList<String>();
        }
        return this.nullFlavor;
    }

    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
            "value"
    })
    public static class HOUSEGUID {

        @XmlValue
        protected String value;

        @XmlAttribute(name = "nullFlavor")
        protected List<String> nullFlavor;

        public String getValue() {
            return value;
        }

        public void setValue(String value) {
            this.value = value;
        }

        public List<String> getNullFlavor() {
            if (nullFlavor == null) {
                nullFlavor = new ArrayList<String>();
            }
            return this.nullFlavor;
        }
    }
}
