//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2022.01.20 at 04:56:34 PM MSK
//

package com.github.akrtkv.semd_demo.dto.semd.fias;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;

@XmlRegistry
public class ObjectFactory {

    private final static QName _Address_QNAME = new QName("urn:hl7-ru:fias", "Address");

    public ObjectFactory() {
    }

    public FiasAddress createFiasAddress() {
        return new FiasAddress();
    }

    public FiasAddress.HOUSEGUID createFiasAddressHOUSEGUID() {
        return new FiasAddress.HOUSEGUID();
    }

    @XmlElementDecl(namespace = "urn:hl7-ru:fias", name = "Address")
    public JAXBElement<FiasAddress> createAddress(FiasAddress value) {
        return new JAXBElement<FiasAddress>(_Address_QNAME, FiasAddress.class, null, value);
    }
}
