//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2022.01.20 at 04:56:34 PM MSK
//

package com.github.akrtkv.semd_demo.dto.semd.medservice;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;

@XmlRegistry
public class ObjectFactory {

    private final static QName _DocType_QNAME = new QName("urn:hl7-ru:medService", "DocType");

    private final static QName _ServiceForm_QNAME = new QName("urn:hl7-ru:medService", "serviceForm");

    private final static QName _ServiceType_QNAME = new QName("urn:hl7-ru:medService", "serviceType");

    private final static QName _ServiceCond_QNAME = new QName("urn:hl7-ru:medService", "serviceCond");

    public ObjectFactory() {
    }

    public DocType createDocType() {
        return new DocType();
    }

    public ServiceForm createServiceForm() {
        return new ServiceForm();
    }

    public ServiceType createServiceType() {
        return new ServiceType();
    }

    public ServiceCond createServiceCond() {
        return new ServiceCond();
    }

    @XmlElementDecl(namespace = "urn:hl7-ru:medService", name = "DocType")
    public JAXBElement<DocType> createDocType(DocType value) {
        return new JAXBElement<DocType>(_DocType_QNAME, DocType.class, null, value);
    }

    @XmlElementDecl(namespace = "urn:hl7-ru:medService", name = "serviceForm")
    public JAXBElement<ServiceForm> createServiceForm(ServiceForm value) {
        return new JAXBElement<ServiceForm>(_ServiceForm_QNAME, ServiceForm.class, null, value);
    }

    @XmlElementDecl(namespace = "urn:hl7-ru:medService", name = "serviceType")
    public JAXBElement<ServiceType> createServiceType(ServiceType value) {
        return new JAXBElement<ServiceType>(_ServiceType_QNAME, ServiceType.class, null, value);
    }

    @XmlElementDecl(namespace = "urn:hl7-ru:medService", name = "serviceCond")
    public JAXBElement<ServiceCond> createServiceCond(ServiceCond value) {
        return new JAXBElement<ServiceCond>(_ServiceCond_QNAME, ServiceCond.class, null, value);
    }
}
