//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.3
// See https://eclipse-ee4j.github.io/jaxb-ri
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2021.08.31 at 03:51:03 PM MSK
//

package com.github.akrtkv.semd_demo.dto.egisz.monetization;

import javax.xml.bind.annotation.*;
import javax.xml.datatype.XMLGregorianCalendar;
import java.util.ArrayList;
import java.util.List;

@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
        "infoSysCode",
        "documents"
})
@XmlRootElement(name = "root")
public class FrLloMonetization {

    @XmlElement(name = "info_sys_code", required = true)
    protected String infoSysCode;

    @XmlElement(required = true)
    protected Documents documents;

    public String getInfoSysCode() {
        return infoSysCode;
    }

    public void setInfoSysCode(String value) {
        this.infoSysCode = value;
    }

    public Documents getDocuments() {
        return documents;
    }

    public void setDocuments(Documents value) {
        this.documents = value;
    }

    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
            "document"
    })
    public static class Documents {

        @XmlElement(required = true)
        protected List<Document> document;

        public List<Document> getDocument() {
            if (document == null) {
                document = new ArrayList<Document>();
            }
            return this.document;
        }

        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
                "documentId",
                "docDateTime",
                "citizen",
                "monetizations"
        })
        public static class Document {

            @XmlElement(name = "document_id", required = true)
            protected String documentId;

            @XmlElement(name = "doc_date_time", required = true)
            protected String docDateTime;

            @XmlElement(required = true)
            protected Citizen citizen;

            @XmlElement(required = true)
            protected Monetizations monetizations;

            public String getDocumentId() {
                return documentId;
            }

            public void setDocumentId(String value) {
                this.documentId = value;
            }

            public String getDocDateTime() {
                return docDateTime;
            }

            public void setDocDateTime(String value) {
                this.docDateTime = value;
            }

            public Citizen getCitizen() {
                return citizen;
            }

            public void setCitizen(Citizen value) {
                this.citizen = value;
            }

            public Monetizations getMonetizations() {
                return monetizations;
            }

            public void setMonetizations(Monetizations value) {
                this.monetizations = value;
            }

            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                    "registerId",
                    "extCitizenId",
                    "name",
                    "surname",
                    "patronymic",
                    "firstsurname",
                    "birthdate",
                    "sex",
                    "snils",
                    "policySn",
                    "identifyDocs",
                    "region"
            })
            public static class Citizen {

                @XmlElement(name = "register_id")
                protected String registerId;

                @XmlElement(name = "ext_citizen_id")
                protected String extCitizenId;

                protected String name;

                protected String surname;

                protected String patronymic;

                protected String firstsurname;

                @XmlSchemaType(name = "date")
                protected XMLGregorianCalendar birthdate;

                protected String sex;

                protected String snils;

                @XmlElement(name = "policy_sn")
                protected String policySn;

                @XmlElement(name = "identify_docs")
                protected IdentifyDocs identifyDocs;

                @XmlElement(required = true)
                protected String region;

                public String getRegisterId() {
                    return registerId;
                }

                public void setRegisterId(String value) {
                    this.registerId = value;
                }

                public String getExtCitizenId() {
                    return extCitizenId;
                }

                public void setExtCitizenId(String value) {
                    this.extCitizenId = value;
                }

                public String getName() {
                    return name;
                }

                public void setName(String value) {
                    this.name = value;
                }

                public String getSurname() {
                    return surname;
                }

                public void setSurname(String value) {
                    this.surname = value;
                }

                public String getPatronymic() {
                    return patronymic;
                }

                public void setPatronymic(String value) {
                    this.patronymic = value;
                }

                public String getFirstsurname() {
                    return firstsurname;
                }

                public void setFirstsurname(String value) {
                    this.firstsurname = value;
                }

                public XMLGregorianCalendar getBirthdate() {
                    return birthdate;
                }

                public void setBirthdate(XMLGregorianCalendar value) {
                    this.birthdate = value;
                }

                public String getSex() {
                    return sex;
                }

                public void setSex(String value) {
                    this.sex = value;
                }

                public String getSnils() {
                    return snils;
                }

                public void setSnils(String value) {
                    this.snils = value;
                }

                public String getPolicySn() {
                    return policySn;
                }

                public void setPolicySn(String value) {
                    this.policySn = value;
                }

                public IdentifyDocs getIdentifyDocs() {
                    return identifyDocs;
                }

                public void setIdentifyDocs(IdentifyDocs value) {
                    this.identifyDocs = value;
                }

                public String getRegion() {
                    return region;
                }

                public void setRegion(String value) {
                    this.region = value;
                }

                @XmlAccessorType(XmlAccessType.FIELD)
                @XmlType(name = "", propOrder = {
                        "doc"
                })
                public static class IdentifyDocs {

                    @XmlElement(required = true)
                    protected List<Doc> doc;

                    public List<Doc> getDoc() {
                        if (doc == null) {
                            doc = new ArrayList<Doc>();
                        }
                        return this.doc;
                    }

                    @XmlAccessorType(XmlAccessType.FIELD)
                    @XmlType(name = "", propOrder = {
                            "docType",
                            "serial",
                            "num",
                            "dateIssue",
                            "authority",
                            "dateExpiry"
                    })
                    public static class Doc {

                        @XmlElement(name = "doc_type", required = true)
                        protected String docType;

                        protected String serial;

                        @XmlElement(required = true)
                        protected String num;

                        @XmlElement(name = "date_issue", required = true)
                        @XmlSchemaType(name = "date")
                        protected XMLGregorianCalendar dateIssue;

                        protected String authority;

                        @XmlElement(name = "date_expiry")
                        @XmlSchemaType(name = "date")
                        protected XMLGregorianCalendar dateExpiry;

                        public String getDocType() {
                            return docType;
                        }

                        public void setDocType(String value) {
                            this.docType = value;
                        }

                        public String getSerial() {
                            return serial;
                        }

                        public void setSerial(String value) {
                            this.serial = value;
                        }

                        public String getNum() {
                            return num;
                        }

                        public void setNum(String value) {
                            this.num = value;
                        }

                        public XMLGregorianCalendar getDateIssue() {
                            return dateIssue;
                        }

                        public void setDateIssue(XMLGregorianCalendar value) {
                            this.dateIssue = value;
                        }

                        public String getAuthority() {
                            return authority;
                        }

                        public void setAuthority(String value) {
                            this.authority = value;
                        }

                        public XMLGregorianCalendar getDateExpiry() {
                            return dateExpiry;
                        }

                        public void setDateExpiry(XMLGregorianCalendar value) {
                            this.dateExpiry = value;
                        }
                    }
                }
            }

            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                    "monetization"
            })
            public static class Monetizations {

                @XmlElement(required = true)
                protected List<Monetization> monetization;

                public List<Monetization> getMonetization() {
                    if (monetization == null) {
                        monetization = new ArrayList<Monetization>();
                    }
                    return this.monetization;
                }

                @XmlAccessorType(XmlAccessType.FIELD)
                @XmlType(name = "", propOrder = {
                        "startDate",
                        "endDate"
                })
                public static class Monetization {

                    @XmlElement(name = "start_date", required = true)
                    @XmlSchemaType(name = "date")
                    protected XMLGregorianCalendar startDate;

                    @XmlElement(name = "end_date")
                    @XmlSchemaType(name = "date")
                    protected XMLGregorianCalendar endDate;

                    public XMLGregorianCalendar getStartDate() {
                        return startDate;
                    }

                    public void setStartDate(XMLGregorianCalendar value) {
                        this.startDate = value;
                    }

                    public XMLGregorianCalendar getEndDate() {
                        return endDate;
                    }

                    public void setEndDate(XMLGregorianCalendar value) {
                        this.endDate = value;
                    }
                }
            }
        }
    }
}
