//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.3
// See https://eclipse-ee4j.github.io/jaxb-ri
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2021.08.31 at 03:51:03 PM MSK
//

package com.github.akrtkv.semd_demo.dto.egisz.monetization;

import javax.xml.bind.annotation.XmlRegistry;

@XmlRegistry
public class ObjectFactory {

    public ObjectFactory() {
    }

    public FrLloMonetization createRoot() {
        return new FrLloMonetization();
    }

    public FrLloMonetization.Documents createRootDocuments() {
        return new FrLloMonetization.Documents();
    }

    public FrLloMonetization.Documents.Document createRootDocumentsDocument() {
        return new FrLloMonetization.Documents.Document();
    }

    public FrLloMonetization.Documents.Document.Monetizations createRootDocumentsDocumentMonetizations() {
        return new FrLloMonetization.Documents.Document.Monetizations();
    }

    public FrLloMonetization.Documents.Document.Citizen createRootDocumentsDocumentCitizen() {
        return new FrLloMonetization.Documents.Document.Citizen();
    }

    public FrLloMonetization.Documents.Document.Citizen.IdentifyDocs createRootDocumentsDocumentCitizenIdentifyDocs() {
        return new FrLloMonetization.Documents.Document.Citizen.IdentifyDocs();
    }

    public FrLloMonetization.Documents.Document.Monetizations.Monetization createRootDocumentsDocumentMonetizationsMonetization() {
        return new FrLloMonetization.Documents.Document.Monetizations.Monetization();
    }

    public FrLloMonetization.Documents.Document.Citizen.IdentifyDocs.Doc createRootDocumentsDocumentCitizenIdentifyDocsDoc() {
        return new FrLloMonetization.Documents.Document.Citizen.IdentifyDocs.Doc();
    }
}
