//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.3
// See https://eclipse-ee4j.github.io/jaxb-ri
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2021.05.26 at 02:55:05 PM MSK
//

package su.medsoft.rir.recipe.dto.egisz.release;

import javax.xml.bind.annotation.XmlRegistry;

@XmlRegistry
public class ObjectFactory {

    public ObjectFactory() {
    }

    public FrLloRelease createRoot() {
        return new FrLloRelease();
    }

    public FrLloRelease.Documents createRootDocuments() {
        return new FrLloRelease.Documents();
    }

    public FrLloRelease.Documents.Document createRootDocumentsDocument() {
        return new FrLloRelease.Documents.Document();
    }

    public FrLloRelease.Documents.Document.Relise createRootDocumentsDocumentRelise() {
        return new FrLloRelease.Documents.Document.Relise();
    }
}
