//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2022.01.20 at 04:56:34 PM MSK
//

package com.github.akrtkv.semd_demo.dto.semd.address;

import com.github.akrtkv.semd_demo.dto.semd.CDAddressStateCode;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;

@XmlRegistry
public class ObjectFactory {

    private final static QName _StateCode_QNAME = new QName("urn:hl7-ru:address", "stateCode");

    private final static QName _Type_QNAME = new QName("urn:hl7-ru:address", "Type");

    private final static QName _ResidentCode_QNAME = new QName("urn:hl7-ru:address", "residentCode");

    public ObjectFactory() {
    }

    public Type createType() {
        return new Type();
    }

    public ResidentCode createResidentCode() {
        return new ResidentCode();
    }

    @XmlElementDecl(namespace = "urn:hl7-ru:address", name = "stateCode")
    public JAXBElement<CDAddressStateCode> createStateCode(CDAddressStateCode value) {
        return new JAXBElement<CDAddressStateCode>(_StateCode_QNAME, CDAddressStateCode.class, null, value);
    }

    @XmlElementDecl(namespace = "urn:hl7-ru:address", name = "Type")
    public JAXBElement<Type> createType(Type value) {
        return new JAXBElement<Type>(_Type_QNAME, Type.class, null, value);
    }

    @XmlElementDecl(namespace = "urn:hl7-ru:address", name = "residentCode")
    public JAXBElement<ResidentCode> createResidentCode(ResidentCode value) {
        return new JAXBElement<ResidentCode>(_ResidentCode_QNAME, ResidentCode.class, null, value);
    }
}
