//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.3
// See https://eclipse-ee4j.github.io/jaxb-ri
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2021.05.26 at 02:54:32 PM MSK
//

package com.github.akrtkv.semd_demo.dto.egisz.benefit;

import javax.xml.bind.annotation.XmlRegistry;

@XmlRegistry
public class ObjectFactory {

    public ObjectFactory() {
    }

    public FrLloBenefit createRoot() {
        return new FrLloBenefit();
    }

    public FrLloBenefit.Documents createRootDocuments() {
        return new FrLloBenefit.Documents();
    }

    public FrLloBenefit.Documents.Document createRootDocumentsDocument() {
        return new FrLloBenefit.Documents.Document();
    }

    public FrLloBenefit.Documents.Document.Benefits createRootDocumentsDocumentBenefits() {
        return new FrLloBenefit.Documents.Document.Benefits();
    }

    public FrLloBenefit.Documents.Document.Citizen createRootDocumentsDocumentCitizen() {
        return new FrLloBenefit.Documents.Document.Citizen();
    }

    public FrLloBenefit.Documents.Document.Citizen.Addresses createRootDocumentsDocumentCitizenAddresses() {
        return new FrLloBenefit.Documents.Document.Citizen.Addresses();
    }

    public FrLloBenefit.Documents.Document.Citizen.IdentifyDocs createRootDocumentsDocumentCitizenIdentifyDocs() {
        return new FrLloBenefit.Documents.Document.Citizen.IdentifyDocs();
    }

    public FrLloBenefit.Documents.Document.Citizen.CitizenshipConfirm createRootDocumentsDocumentCitizenCitizenshipConfirm() {
        return new FrLloBenefit.Documents.Document.Citizen.CitizenshipConfirm();
    }

    public FrLloBenefit.Documents.Document.Benefits.Benefit createRootDocumentsDocumentBenefitsBenefit() {
        return new FrLloBenefit.Documents.Document.Benefits.Benefit();
    }

    public FrLloBenefit.Documents.Document.Citizen.Addresses.Address createRootDocumentsDocumentCitizenAddressesAddress() {
        return new FrLloBenefit.Documents.Document.Citizen.Addresses.Address();
    }

    public FrLloBenefit.Documents.Document.Citizen.IdentifyDocs.Doc createRootDocumentsDocumentCitizenIdentifyDocsDoc() {
        return new FrLloBenefit.Documents.Document.Citizen.IdentifyDocs.Doc();
    }

    public FrLloBenefit.Documents.Document.Citizen.CitizenshipConfirm.Doc createRootDocumentsDocumentCitizenCitizenshipConfirmDoc() {
        return new FrLloBenefit.Documents.Document.Citizen.CitizenshipConfirm.Doc();
    }
}
