//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.3
// See https://eclipse-ee4j.github.io/jaxb-ri
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2021.05.26 at 03:55:40 PM MSK
//

package com.github.akrtkv.semd_demo.dto.egisz.callback;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;

@XmlRegistry
public class ObjectFactory {

    private final static QName _SendResponse_QNAME = new QName("http://emu.callback.mis.service.nr.eu.rt.ru/", "sendResponse");

    private final static QName _SendResponseResponse_QNAME = new QName("http://emu.callback.mis.service.nr.eu.rt.ru/", "sendResponseResponse");

    public ObjectFactory() {
    }

    public SendResponse createSendResponse() {
        return new SendResponse();
    }

    public SendResponseResponse createSendResponseResponse() {
        return new SendResponseResponse();
    }

    @XmlElementDecl(namespace = "http://emu.callback.mis.service.nr.eu.rt.ru/", name = "sendResponse")
    public JAXBElement<SendResponse> createSendResponse(SendResponse value) {
        return new JAXBElement<SendResponse>(_SendResponse_QNAME, SendResponse.class, null, value);
    }

    @XmlElementDecl(namespace = "http://emu.callback.mis.service.nr.eu.rt.ru/", name = "sendResponseResponse")
    public JAXBElement<SendResponseResponse> createSendResponseResponse(SendResponseResponse value) {
        return new JAXBElement<SendResponseResponse>(_SendResponseResponse_QNAME, SendResponseResponse.class, null, value);
    }
}
