//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.3
// See https://eclipse-ee4j.github.io/jaxb-ri
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2021.05.26 at 03:55:40 PM MSK
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://emu.callback.mis.service.nr.eu.rt.ru/")
package com.github.akrtkv.semd_demo.dto.egisz.callback;
