//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.3
// See https://eclipse-ee4j.github.io/jaxb-ri
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2021.05.26 at 02:54:49 PM MSK
//

package su.medsoft.rir.recipe.dto.egisz.recipe;

import javax.xml.bind.annotation.XmlRegistry;

@XmlRegistry
public class ObjectFactory {

    public ObjectFactory() {
    }

    public FrLloRecipe createRoot() {
        return new FrLloRecipe();
    }

    public FrLloRecipe.Documents createRootDocuments() {
        return new FrLloRecipe.Documents();
    }

    public FrLloRecipe.Documents.Document createRootDocumentsDocument() {
        return new FrLloRecipe.Documents.Document();
    }

    public FrLloRecipe.Documents.Document.Citizen createRootDocumentsDocumentCitizen() {
        return new FrLloRecipe.Documents.Document.Citizen();
    }

    public FrLloRecipe.Documents.Document.Citizen.IdentifyDocs createRootDocumentsDocumentCitizenIdentifyDocs() {
        return new FrLloRecipe.Documents.Document.Citizen.IdentifyDocs();
    }

    public FrLloRecipe.Documents.Document.Recipe createRootDocumentsDocumentRecipe() {
        return new FrLloRecipe.Documents.Document.Recipe();
    }

    public FrLloRecipe.Documents.Document.Citizen.IdentifyDocs.Doc createRootDocumentsDocumentCitizenIdentifyDocsDoc() {
        return new FrLloRecipe.Documents.Document.Citizen.IdentifyDocs.Doc();
    }
}
